# Two POVs + Trainable Feature Extractor with Regression Head

In [1]:
import math
import datetime
from sklearn.metrics import mean_squared_error, r2_score
from itertools import product
from tqdm import tqdm
from src.constants import *
from src.helpers import *
from src.trainable_pipeline import *

seed_everything(RANDOM_STATE)

## Load Data

In [2]:
samples, image_paths = load_image_paths(CSV_PATH, TOP_FOLDER, SIDE_FOLDER)
print("Samples shape:", samples.shape)
display(samples[["exp_id", "volume", "top_path", "side_path"]].head())

Samples shape: (140, 23)

,exp_id,volume,top_path,side_path
0,1,38,photos/top_view_images/P2090072.JPG,photos/side_view_images/P2090161.JPG
1,1,57,photos/top_view_images/P2090073.JPG,photos/side_view_images/P2090163.JPG
2,1,76,photos/top_view_images/P2090074.JPG,photos/side_view_images/P2090167.JPG
3,2,19,photos/top_view_images/P2090075.JPG,photos/side_view_images/P2090171.JPG
4,2,38,photos/top_view_images/P2090076.JPG,photos/side_view_images/P2090173.JPG

In [3]:
def evaluate_setting_nested_cv(samples_df, backbone_name, fusion_name, head_name, mode_name):
    y = samples_df["volume"].to_numpy(dtype=float)
    groups = samples_df["exp_id"].to_numpy()

    outer_cv = GroupKFold(n_splits=OUTER_SPLITS)
    outer_splits = list(outer_cv.split(np.zeros((len(samples_df), 1)), y, groups))
    fold_records = []
    oof_pred = np.full(len(samples_df), np.nan, dtype=float)

    print("=" * 90)
    print(backbone_name, fusion_name, head_name, mode_name)
    print("=" * 90)

    for fold_idx, (train_idx, test_idx) in enumerate(
        tqdm(outer_splits,
            total=len(outer_splits),
            desc=f"{backbone_name} | {fusion_name} | {head_name} | {mode_name}",),
        start=1,
    ):
        train_groups = groups[train_idx]
        n_inner = min(INNER_SPLITS, len(np.unique(train_groups)))
        inner_cv = GroupKFold(n_splits=n_inner)

        best_cfg = None
        best_inner_mae = float("inf")

        for cfg in TRAINING_CONFIGS[mode_name]:
            inner_maes = []
            for inner_train_rel, inner_val_rel in inner_cv.split(np.zeros((len(train_idx), 1)), y[train_idx], train_groups):
                inner_train_idx = train_idx[inner_train_rel]
                inner_val_idx = train_idx[inner_val_rel]
                backbone, head, preprocess, inner_val_mae = fit_model(
                    samples_df=samples_df,
                    train_idx=inner_train_idx,
                    val_idx=inner_val_idx,
                    backbone_name=backbone_name,
                    fusion_name=fusion_name,
                    head_name=head_name,
                    mode_name=mode_name,
                    cfg=cfg,
                    head_cfg=HEAD_CONFIGS[head_name],
                    batch_size=BATCH_SIZE,
                    max_epochs=MAX_EPOCHS,
                    seed=RANDOM_STATE + fold_idx,
                    device=DEVICE,
                )
                inner_maes.append(inner_val_mae)
                del backbone, head
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

            mean_inner_mae = float(np.mean(inner_maes))
            if mean_inner_mae < best_inner_mae:
                best_inner_mae = mean_inner_mae
                best_cfg = cfg

        final_train_idx, final_val_idx = make_group_train_val_split(train_idx, groups, seed=RANDOM_STATE + fold_idx)
        backbone, head, preprocess, _ = fit_model(
            samples_df=samples_df,
            train_idx=final_train_idx,
            val_idx=final_val_idx,
            backbone_name=backbone_name,
            fusion_name=fusion_name,
            head_name=head_name,
            mode_name=mode_name,
            cfg=best_cfg,
            head_cfg=HEAD_CONFIGS[head_name],
            batch_size=BATCH_SIZE,
            max_epochs=MAX_EPOCHS,
            seed=RANDOM_STATE + fold_idx,
            device=DEVICE,
        )

        y_test_true, y_test_pred = predict_indices(samples_df, test_idx, preprocess, backbone_name, backbone, head, fusion_name, BATCH_SIZE, DEVICE)
        oof_pred[test_idx] = y_test_pred

        record = {
            "fold": fold_idx,
            "backbone": backbone_name,
            "fusion": fusion_name,
            "head": head_name,
            "mode": mode_name,
            "inner_MAE": best_inner_mae,
            "MAE": mean_absolute_error(y_test_true, y_test_pred),
            "MSE": mean_squared_error(y_test_true, y_test_pred),
            "RMSE": math.sqrt(mean_squared_error(y_test_true, y_test_pred)),
            "R2": r2_score(y_test_true, y_test_pred) if len(np.unique(y_test_true)) > 1 else np.nan,
            "best_cfg": best_cfg,
        }
        fold_records.append(record)

        print(f"Fold {fold_idx}: MAE={record['MAE']:.3f}, RMSE={record['RMSE']:.3f}, R2={record['R2']}, best={best_cfg}")

        del backbone, head
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return fold_records, oof_pred

def summarise_records(records):
    rows = []
    grouped = {}
    for rec in records:
        key = (rec["backbone"], rec["fusion"], rec["head"], rec["mode"])
        grouped.setdefault(key, []).append(rec)

    for (backbone, fusion, head, mode), folds in grouped.items():
        rows.append({
            "backbone": backbone,
            "fusion": fusion,
            "head": head,
            "mode": mode,
            "cv_mae_mean": np.mean([f["MAE"] for f in folds]),
            "cv_mae_std": np.std([f["MAE"] for f in folds]),
            "cv_rmse_mean": np.mean([f["RMSE"] for f in folds]),
            "cv_rmse_std": np.std([f["RMSE"] for f in folds]),
            "cv_r2_mean": np.mean([f["R2"] for f in folds]),
            "cv_r2_std": np.std([f["R2"] for f in folds]),
            "inner_mae_mean": np.mean([f["inner_MAE"] for f in folds]),
        })

    return pd.DataFrame(rows).sort_values("cv_mae_mean").reset_index(drop=True)

In [4]:
all_fold_records = []
oof_store = {}

all_configs = list(product(
    BACKBONE_NAMES,
    FUSION_NAMES,
    HEAD_CONFIGS.keys(),
    TRAINING_CONFIGS.keys()
))


for backbone_name, fusion_name, head_name, mode_name in tqdm(all_configs, desc="Experiment configs"):
    print(f"\n=== {backbone_name} | {fusion_name} | {head_name} | {mode_name} ===")
    fold_records, oof_pred = evaluate_setting_nested_cv(
        samples_df=samples,
        backbone_name=backbone_name,
        fusion_name=fusion_name,
        head_name=head_name,
        mode_name=mode_name,
    )
    all_fold_records.extend(fold_records)
    oof_store[(backbone_name, fusion_name, head_name, mode_name)] = oof_pred

summary_df = summarise_records(all_fold_records)
summary_df

Experiment configs:   0%|          | 0/1 [00:00<?, ?it/s]

=== vit_b_16 | concat | mlp | last_stage ===
==========================================================================================
vit_b_16 concat mlp last_stage
==========================================================================================

vit_b_16 | concat | mlp | last_stage:   0%|          | 0/5 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=35.55, patience=6, val=35.55]

Epochs:   5%|▌         | 1/20 [00:28<08:52, 28.02s/it, best=35.55, patience=6, val=35.55]

Epochs:   5%|▌         | 1/20 [00:52<08:52, 28.02s/it, best=22.66, patience=6, val=22.66]

Epochs:  10%|█         | 2/20 [00:52<07:44, 25.78s/it, best=22.66, patience=6, val=22.66]

Epochs:  10%|█         | 2/20 [01:19<07:44, 25.78s/it, best=18.00, patience=6, val=18.00]

Epochs:  15%|█▌        | 3/20 [01:19<07:28, 26.36s/it, best=18.00, patience=6, val=18.00]

Epochs:  15%|█▌        | 3/20 [01:47<07:28, 26.36s/it, best=16.45, patience=6, val=16.45]

Epochs:  20%|██        | 4/20 [01:47<07:10, 26.93s/it, best=16.45, patience=6, val=16.45]

Epochs:  20%|██        | 4/20 [02:14<07:10, 26.93s/it, best=14.65, patience=6, val=14.65]

Epochs:  25%|██▌       | 5/20 [02:14<06:47, 27.14s/it, best=14.65, patience=6, val=14.65]

Epochs:  25%|██▌       | 5/20 [02:41<06:47, 27.14s/it, best=12.89, patience=6, val=12.89]

Epochs:  30%|███       | 6/20 [02:41<06:20, 27.21s/it, best=12.89, patience=6, val=12.89]

Epochs:  30%|███       | 6/20 [03:09<06:20, 27.21s/it, best=11.25, patience=6, val=11.25]

Epochs:  35%|███▌      | 7/20 [03:09<05:55, 27.36s/it, best=11.25, patience=6, val=11.25]

Epochs:  35%|███▌      | 7/20 [03:37<05:55, 27.36s/it, best=10.03, patience=6, val=10.03]

Epochs:  40%|████      | 8/20 [03:37<05:29, 27.43s/it, best=10.03, patience=6, val=10.03]

Epochs:  40%|████      | 8/20 [04:05<05:29, 27.43s/it, best=8.84, patience=6, val=8.84]

Epochs:  45%|████▌     | 9/20 [04:05<05:03, 27.58s/it, best=8.84, patience=6, val=8.84]

Epochs:  45%|████▌     | 9/20 [04:32<05:03, 27.58s/it, best=7.75, patience=6, val=7.75]

Epochs:  50%|█████     | 10/20 [04:32<04:36, 27.65s/it, best=7.75, patience=6, val=7.75]

Epochs:  50%|█████     | 10/20 [05:00<04:36, 27.65s/it, best=6.65, patience=6, val=6.65]

Epochs:  55%|█████▌    | 11/20 [05:00<04:09, 27.74s/it, best=6.65, patience=6, val=6.65]

Epochs:  55%|█████▌    | 11/20 [05:28<04:09, 27.74s/it, best=6.59, patience=6, val=6.59]

Epochs:  60%|██████    | 12/20 [05:28<03:42, 27.81s/it, best=6.59, patience=6, val=6.59]

Epochs:  60%|██████    | 12/20 [05:56<03:42, 27.81s/it, best=6.12, patience=6, val=6.12]

Epochs:  65%|██████▌   | 13/20 [05:56<03:14, 27.81s/it, best=6.12, patience=6, val=6.12]

Epochs:  65%|██████▌   | 13/20 [06:24<03:14, 27.81s/it, best=6.12, patience=5, val=7.56]

Epochs:  70%|███████   | 14/20 [06:24<02:47, 27.87s/it, best=6.12, patience=5, val=7.56]

Epochs:  70%|███████   | 14/20 [06:53<02:47, 27.87s/it, best=5.79, patience=6, val=5.79]

Epochs:  75%|███████▌  | 15/20 [06:53<02:20, 28.03s/it, best=5.79, patience=6, val=5.79]

Epochs:  75%|███████▌  | 15/20 [07:21<02:20, 28.03s/it, best=5.59, patience=6, val=5.59]

Epochs:  80%|████████  | 16/20 [07:21<01:52, 28.07s/it, best=5.59, patience=6, val=5.59]

Epochs:  80%|████████  | 16/20 [07:49<01:52, 28.07s/it, best=5.58, patience=6, val=5.58]

Epochs:  85%|████████▌ | 17/20 [07:49<01:24, 28.06s/it, best=5.58, patience=6, val=5.58]

Epochs:  85%|████████▌ | 17/20 [08:17<01:24, 28.06s/it, best=5.36, patience=6, val=5.36]

Epochs:  90%|█████████ | 18/20 [08:17<00:56, 28.04s/it, best=5.36, patience=6, val=5.36]

Epochs:  90%|█████████ | 18/20 [08:45<00:56, 28.04s/it, best=5.36, patience=5, val=5.53]

Epochs:  95%|█████████▌| 19/20 [08:45<00:28, 28.09s/it, best=5.36, patience=5, val=5.53]

Epochs:  95%|█████████▌| 19/20 [09:13<00:28, 28.09s/it, best=5.06, patience=6, val=5.06]

Epochs: 100%|██████████| 20/20 [09:13<00:00, 28.14s/it, best=5.06, patience=6, val=5.06]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:26<?, ?it/s, best=34.92, patience=6, val=34.92]

Epochs:   5%|▌         | 1/20 [00:26<08:22, 26.43s/it, best=34.92, patience=6, val=34.92]

Epochs:   5%|▌         | 1/20 [00:52<08:22, 26.43s/it, best=21.40, patience=6, val=21.40]

Epochs:  10%|█         | 2/20 [00:52<07:54, 26.35s/it, best=21.40, patience=6, val=21.40]

Epochs:  10%|█         | 2/20 [01:18<07:54, 26.35s/it, best=17.08, patience=6, val=17.08]

Epochs:  15%|█▌        | 3/20 [01:18<07:26, 26.28s/it, best=17.08, patience=6, val=17.08]

Epochs:  15%|█▌        | 3/20 [01:45<07:26, 26.28s/it, best=15.69, patience=6, val=15.69]

Epochs:  20%|██        | 4/20 [01:45<07:01, 26.34s/it, best=15.69, patience=6, val=15.69]

Epochs:  20%|██        | 4/20 [02:11<07:01, 26.34s/it, best=14.06, patience=6, val=14.06]

Epochs:  25%|██▌       | 5/20 [02:11<06:36, 26.41s/it, best=14.06, patience=6, val=14.06]

Epochs:  25%|██▌       | 5/20 [02:38<06:36, 26.41s/it, best=12.34, patience=6, val=12.34]

Epochs:  30%|███       | 6/20 [02:38<06:09, 26.42s/it, best=12.34, patience=6, val=12.34]

Epochs:  30%|███       | 6/20 [03:04<06:09, 26.42s/it, best=10.61, patience=6, val=10.61]

Epochs:  35%|███▌      | 7/20 [03:04<05:44, 26.48s/it, best=10.61, patience=6, val=10.61]

Epochs:  35%|███▌      | 7/20 [03:31<05:44, 26.48s/it, best=9.51, patience=6, val=9.51]

Epochs:  40%|████      | 8/20 [03:31<05:17, 26.46s/it, best=9.51, patience=6, val=9.51]

Epochs:  40%|████      | 8/20 [03:58<05:17, 26.46s/it, best=8.36, patience=6, val=8.36]

Epochs:  45%|████▌     | 9/20 [03:58<04:52, 26.56s/it, best=8.36, patience=6, val=8.36]

Epochs:  45%|████▌     | 9/20 [04:24<04:52, 26.56s/it, best=8.02, patience=6, val=8.02]

Epochs:  50%|█████     | 10/20 [04:24<04:25, 26.53s/it, best=8.02, patience=6, val=8.02]

Epochs:  50%|█████     | 10/20 [04:51<04:25, 26.53s/it, best=7.35, patience=6, val=7.35]

Epochs:  55%|█████▌    | 11/20 [04:51<03:59, 26.65s/it, best=7.35, patience=6, val=7.35]

Epochs:  55%|█████▌    | 11/20 [05:18<03:59, 26.65s/it, best=7.30, patience=6, val=7.30]

Epochs:  60%|██████    | 12/20 [05:18<03:33, 26.74s/it, best=7.30, patience=6, val=7.30]

Epochs:  60%|██████    | 12/20 [05:45<03:33, 26.74s/it, best=7.30, patience=5, val=7.42]

Epochs:  65%|██████▌   | 13/20 [05:45<03:07, 26.73s/it, best=7.30, patience=5, val=7.42]

Epochs:  65%|██████▌   | 13/20 [06:11<03:07, 26.73s/it, best=7.01, patience=6, val=7.01]

Epochs:  70%|███████   | 14/20 [06:11<02:40, 26.75s/it, best=7.01, patience=6, val=7.01]

Epochs:  70%|███████   | 14/20 [06:38<02:40, 26.75s/it, best=6.64, patience=6, val=6.64]

Epochs:  75%|███████▌  | 15/20 [06:38<02:14, 26.83s/it, best=6.64, patience=6, val=6.64]

Epochs:  75%|███████▌  | 15/20 [07:05<02:14, 26.83s/it, best=6.44, patience=6, val=6.44]

Epochs:  80%|████████  | 16/20 [07:05<01:47, 26.86s/it, best=6.44, patience=6, val=6.44]

Epochs:  80%|████████  | 16/20 [07:32<01:47, 26.86s/it, best=6.30, patience=6, val=6.30]

Epochs:  85%|████████▌ | 17/20 [07:32<01:20, 26.70s/it, best=6.30, patience=6, val=6.30]

Epochs:  85%|████████▌ | 17/20 [07:58<01:20, 26.70s/it, best=6.30, patience=5, val=6.31]

Epochs:  90%|█████████ | 18/20 [07:58<00:53, 26.68s/it, best=6.30, patience=5, val=6.31]

Epochs:  90%|█████████ | 18/20 [08:25<00:53, 26.68s/it, best=6.18, patience=6, val=6.18]

Epochs:  95%|█████████▌| 19/20 [08:25<00:26, 26.64s/it, best=6.18, patience=6, val=6.18]

Epochs:  95%|█████████▌| 19/20 [08:51<00:26, 26.64s/it, best=6.18, patience=5, val=6.68]

Epochs: 100%|██████████| 20/20 [08:51<00:00, 26.61s/it, best=6.18, patience=5, val=6.68]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:26<?, ?it/s, best=33.91, patience=6, val=33.91]

Epochs:   5%|▌         | 1/20 [00:26<08:23, 26.53s/it, best=33.91, patience=6, val=33.91]

Epochs:   5%|▌         | 1/20 [00:53<08:23, 26.53s/it, best=21.07, patience=6, val=21.07]

Epochs:  10%|█         | 2/20 [00:53<08:02, 26.78s/it, best=21.07, patience=6, val=21.07]

Epochs:  10%|█         | 2/20 [01:20<08:02, 26.78s/it, best=16.96, patience=6, val=16.96]

Epochs:  15%|█▌        | 3/20 [01:20<07:39, 27.03s/it, best=16.96, patience=6, val=16.96]

Epochs:  15%|█▌        | 3/20 [01:47<07:39, 27.03s/it, best=15.82, patience=6, val=15.82]

Epochs:  20%|██        | 4/20 [01:47<07:11, 26.97s/it, best=15.82, patience=6, val=15.82]

Epochs:  20%|██        | 4/20 [02:14<07:11, 26.97s/it, best=14.20, patience=6, val=14.20]

Epochs:  25%|██▌       | 5/20 [02:14<06:44, 26.99s/it, best=14.20, patience=6, val=14.20]

Epochs:  25%|██▌       | 5/20 [02:41<06:44, 26.99s/it, best=12.75, patience=6, val=12.75]

Epochs:  30%|███       | 6/20 [02:41<06:18, 27.03s/it, best=12.75, patience=6, val=12.75]

Epochs:  30%|███       | 6/20 [03:08<06:18, 27.03s/it, best=11.77, patience=6, val=11.77]

Epochs:  35%|███▌      | 7/20 [03:08<05:51, 27.04s/it, best=11.77, patience=6, val=11.77]

Epochs:  35%|███▌      | 7/20 [03:38<05:51, 27.04s/it, best=10.66, patience=6, val=10.66]

Epochs:  40%|████      | 8/20 [03:38<05:32, 27.71s/it, best=10.66, patience=6, val=10.66]

Epochs:  40%|████      | 8/20 [04:08<05:32, 27.71s/it, best=10.00, patience=6, val=10.00]

Epochs:  45%|████▌     | 9/20 [04:08<05:14, 28.62s/it, best=10.00, patience=6, val=10.00]

Epochs:  45%|████▌     | 9/20 [04:38<05:14, 28.62s/it, best=9.53, patience=6, val=9.53]

Epochs:  50%|█████     | 10/20 [04:38<04:50, 29.03s/it, best=9.53, patience=6, val=9.53]

Epochs:  50%|█████     | 10/20 [05:08<04:50, 29.03s/it, best=9.53, patience=5, val=9.64]

Epochs:  55%|█████▌    | 11/20 [05:08<04:22, 29.15s/it, best=9.53, patience=5, val=9.64]

Epochs:  55%|█████▌    | 11/20 [05:37<04:22, 29.15s/it, best=9.53, patience=4, val=9.74]

Epochs:  60%|██████    | 12/20 [05:37<03:53, 29.13s/it, best=9.53, patience=4, val=9.74]

Epochs:  60%|██████    | 12/20 [06:05<03:53, 29.13s/it, best=9.53, patience=3, val=9.99]

Epochs:  65%|██████▌   | 13/20 [06:05<03:23, 29.00s/it, best=9.53, patience=3, val=9.99]

Epochs:  65%|██████▌   | 13/20 [06:36<03:23, 29.00s/it, best=9.53, patience=2, val=9.55]

Epochs:  70%|███████   | 14/20 [06:36<02:56, 29.42s/it, best=9.53, patience=2, val=9.55]

Epochs:  70%|███████   | 14/20 [07:05<02:56, 29.42s/it, best=9.53, patience=6, val=9.53]

Epochs:  75%|███████▌  | 15/20 [07:05<02:26, 29.28s/it, best=9.53, patience=6, val=9.53]

Epochs:  75%|███████▌  | 15/20 [07:33<02:26, 29.28s/it, best=9.53, patience=6, val=9.53]

Epochs:  80%|████████  | 16/20 [07:33<01:56, 29.07s/it, best=9.53, patience=6, val=9.53]

Epochs:  80%|████████  | 16/20 [08:02<01:56, 29.07s/it, best=9.25, patience=6, val=9.25]

Epochs:  85%|████████▌ | 17/20 [08:02<01:26, 28.95s/it, best=9.25, patience=6, val=9.25]

Epochs:  85%|████████▌ | 17/20 [08:30<01:26, 28.95s/it, best=9.14, patience=6, val=9.14]

Epochs:  90%|█████████ | 18/20 [08:30<00:57, 28.80s/it, best=9.14, patience=6, val=9.14]

Epochs:  90%|█████████ | 18/20 [08:59<00:57, 28.80s/it, best=9.01, patience=6, val=9.01]

Epochs:  95%|█████████▌| 19/20 [08:59<00:28, 28.82s/it, best=9.01, patience=6, val=9.01]

Epochs:  95%|█████████▌| 19/20 [09:28<00:28, 28.82s/it, best=9.01, patience=5, val=9.29]

Epochs: 100%|██████████| 20/20 [09:28<00:00, 28.70s/it, best=9.01, patience=5, val=9.29]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=36.92, patience=6, val=36.92]

Epochs:   5%|▌         | 1/20 [00:28<08:57, 28.30s/it, best=36.92, patience=6, val=36.92]

Epochs:   5%|▌         | 1/20 [00:56<08:57, 28.30s/it, best=23.46, patience=6, val=23.46]

Epochs:  10%|█         | 2/20 [00:56<08:32, 28.45s/it, best=23.46, patience=6, val=23.46]

Epochs:  10%|█         | 2/20 [01:25<08:32, 28.45s/it, best=16.53, patience=6, val=16.53]

Epochs:  15%|█▌        | 3/20 [01:25<08:06, 28.63s/it, best=16.53, patience=6, val=16.53]

Epochs:  15%|█▌        | 3/20 [01:53<08:06, 28.63s/it, best=14.90, patience=6, val=14.90]

Epochs:  20%|██        | 4/20 [01:53<07:35, 28.45s/it, best=14.90, patience=6, val=14.90]

Epochs:  20%|██        | 4/20 [02:22<07:35, 28.45s/it, best=13.60, patience=6, val=13.60]

Epochs:  25%|██▌       | 5/20 [02:22<07:05, 28.40s/it, best=13.60, patience=6, val=13.60]

Epochs:  25%|██▌       | 5/20 [02:50<07:05, 28.40s/it, best=13.07, patience=6, val=13.07]

Epochs:  30%|███       | 6/20 [02:50<06:37, 28.41s/it, best=13.07, patience=6, val=13.07]

Epochs:  30%|███       | 6/20 [03:18<06:37, 28.41s/it, best=12.00, patience=6, val=12.00]

Epochs:  35%|███▌      | 7/20 [03:18<06:08, 28.34s/it, best=12.00, patience=6, val=12.00]

Epochs:  35%|███▌      | 7/20 [03:47<06:08, 28.34s/it, best=10.75, patience=6, val=10.75]

Epochs:  40%|████      | 8/20 [03:47<05:40, 28.35s/it, best=10.75, patience=6, val=10.75]

Epochs:  40%|████      | 8/20 [04:15<05:40, 28.35s/it, best=10.23, patience=6, val=10.23]

Epochs:  45%|████▌     | 9/20 [04:15<05:11, 28.28s/it, best=10.23, patience=6, val=10.23]

Epochs:  45%|████▌     | 9/20 [04:44<05:11, 28.28s/it, best=10.09, patience=6, val=10.09]

Epochs:  50%|█████     | 10/20 [04:44<04:44, 28.47s/it, best=10.09, patience=6, val=10.09]

Epochs:  50%|█████     | 10/20 [05:12<04:44, 28.47s/it, best=9.35, patience=6, val=9.35]

Epochs:  55%|█████▌    | 11/20 [05:12<04:17, 28.57s/it, best=9.35, patience=6, val=9.35]

Epochs:  55%|█████▌    | 11/20 [05:41<04:17, 28.57s/it, best=9.19, patience=6, val=9.19]

Epochs:  60%|██████    | 12/20 [05:41<03:47, 28.46s/it, best=9.19, patience=6, val=9.19]

Epochs:  60%|██████    | 12/20 [06:09<03:47, 28.46s/it, best=8.92, patience=6, val=8.92]

Epochs:  65%|██████▌   | 13/20 [06:09<03:19, 28.48s/it, best=8.92, patience=6, val=8.92]

Epochs:  65%|██████▌   | 13/20 [06:38<03:19, 28.48s/it, best=8.17, patience=6, val=8.17]

Epochs:  70%|███████   | 14/20 [06:38<02:50, 28.46s/it, best=8.17, patience=6, val=8.17]

Epochs:  70%|███████   | 14/20 [07:06<02:50, 28.46s/it, best=8.17, patience=5, val=8.29]

Epochs:  75%|███████▌  | 15/20 [07:06<02:22, 28.43s/it, best=8.17, patience=5, val=8.29]

Epochs:  75%|███████▌  | 15/20 [07:34<02:22, 28.43s/it, best=8.17, patience=4, val=8.31]

Epochs:  80%|████████  | 16/20 [07:34<01:53, 28.42s/it, best=8.17, patience=4, val=8.31]

Epochs:  80%|████████  | 16/20 [08:03<01:53, 28.42s/it, best=7.75, patience=6, val=7.75]

Epochs:  85%|████████▌ | 17/20 [08:03<01:25, 28.36s/it, best=7.75, patience=6, val=7.75]

Epochs:  85%|████████▌ | 17/20 [08:31<01:25, 28.36s/it, best=7.70, patience=6, val=7.70]

Epochs:  90%|█████████ | 18/20 [08:31<00:56, 28.36s/it, best=7.70, patience=6, val=7.70]

Epochs:  90%|█████████ | 18/20 [08:59<00:56, 28.36s/it, best=7.70, patience=5, val=7.97]

Epochs:  95%|█████████▌| 19/20 [08:59<00:28, 28.31s/it, best=7.70, patience=5, val=7.97]

Epochs:  95%|█████████▌| 19/20 [09:28<00:28, 28.31s/it, best=7.70, patience=4, val=7.72]

Epochs: 100%|██████████| 20/20 [09:28<00:00, 28.34s/it, best=7.70, patience=4, val=7.72]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=35.73, patience=6, val=35.73]

Epochs:   5%|▌         | 1/20 [00:28<08:56, 28.22s/it, best=35.73, patience=6, val=35.73]

Epochs:   5%|▌         | 1/20 [00:56<08:56, 28.22s/it, best=22.07, patience=6, val=22.07]

Epochs:  10%|█         | 2/20 [00:56<08:32, 28.48s/it, best=22.07, patience=6, val=22.07]

Epochs:  10%|█         | 2/20 [01:25<08:32, 28.48s/it, best=17.25, patience=6, val=17.25]

Epochs:  15%|█▌        | 3/20 [01:25<08:04, 28.48s/it, best=17.25, patience=6, val=17.25]

Epochs:  15%|█▌        | 3/20 [01:53<08:04, 28.48s/it, best=15.76, patience=6, val=15.76]

Epochs:  20%|██        | 4/20 [01:53<07:33, 28.36s/it, best=15.76, patience=6, val=15.76]

Epochs:  20%|██        | 4/20 [02:21<07:33, 28.36s/it, best=14.14, patience=6, val=14.14]

Epochs:  25%|██▌       | 5/20 [02:21<07:05, 28.39s/it, best=14.14, patience=6, val=14.14]

Epochs:  25%|██▌       | 5/20 [02:50<07:05, 28.39s/it, best=12.55, patience=6, val=12.55]

Epochs:  30%|███       | 6/20 [02:50<06:36, 28.30s/it, best=12.55, patience=6, val=12.55]

Epochs:  30%|███       | 6/20 [03:18<06:36, 28.30s/it, best=10.90, patience=6, val=10.90]

Epochs:  35%|███▌      | 7/20 [03:18<06:08, 28.33s/it, best=10.90, patience=6, val=10.90]

Epochs:  35%|███▌      | 7/20 [03:47<06:08, 28.33s/it, best=9.55, patience=6, val=9.55]

Epochs:  40%|████      | 8/20 [03:47<05:40, 28.41s/it, best=9.55, patience=6, val=9.55]

Epochs:  40%|████      | 8/20 [04:15<05:40, 28.41s/it, best=8.75, patience=6, val=8.75]

Epochs:  45%|████▌     | 9/20 [04:15<05:13, 28.47s/it, best=8.75, patience=6, val=8.75]

Epochs:  45%|████▌     | 9/20 [04:43<05:13, 28.47s/it, best=8.30, patience=6, val=8.30]

Epochs:  50%|█████     | 10/20 [04:43<04:44, 28.42s/it, best=8.30, patience=6, val=8.30]

Epochs:  50%|█████     | 10/20 [05:12<04:44, 28.42s/it, best=8.12, patience=6, val=8.12]

Epochs:  55%|█████▌    | 11/20 [05:12<04:16, 28.55s/it, best=8.12, patience=6, val=8.12]

Epochs:  55%|█████▌    | 11/20 [05:41<04:16, 28.55s/it, best=7.58, patience=6, val=7.58]

Epochs:  60%|██████    | 12/20 [05:41<03:48, 28.51s/it, best=7.58, patience=6, val=7.58]

Epochs:  60%|██████    | 12/20 [06:09<03:48, 28.51s/it, best=7.58, patience=5, val=7.75]

Epochs:  65%|██████▌   | 13/20 [06:09<03:19, 28.47s/it, best=7.58, patience=5, val=7.75]

Epochs:  65%|██████▌   | 13/20 [06:38<03:19, 28.47s/it, best=7.58, patience=4, val=7.58]

Epochs:  70%|███████   | 14/20 [06:38<02:50, 28.49s/it, best=7.58, patience=4, val=7.58]

Epochs:  70%|███████   | 14/20 [07:06<02:50, 28.49s/it, best=7.58, patience=3, val=7.96]

Epochs:  75%|███████▌  | 15/20 [07:06<02:22, 28.53s/it, best=7.58, patience=3, val=7.96]

Epochs:  75%|███████▌  | 15/20 [07:35<02:22, 28.53s/it, best=7.38, patience=6, val=7.38]

Epochs:  80%|████████  | 16/20 [07:35<01:53, 28.49s/it, best=7.38, patience=6, val=7.38]

Epochs:  80%|████████  | 16/20 [08:03<01:53, 28.49s/it, best=7.38, patience=5, val=7.53]

Epochs:  85%|████████▌ | 17/20 [08:03<01:25, 28.53s/it, best=7.38, patience=5, val=7.53]

Epochs:  85%|████████▌ | 17/20 [08:32<01:25, 28.53s/it, best=7.34, patience=6, val=7.34]

Epochs:  90%|█████████ | 18/20 [08:32<00:57, 28.53s/it, best=7.34, patience=6, val=7.34]

Epochs:  90%|█████████ | 18/20 [09:01<00:57, 28.53s/it, best=7.18, patience=6, val=7.18]

Epochs:  95%|█████████▌| 19/20 [09:01<00:28, 28.62s/it, best=7.18, patience=6, val=7.18]

Epochs:  95%|█████████▌| 19/20 [09:29<00:28, 28.62s/it, best=6.87, patience=6, val=6.87]

Epochs: 100%|██████████| 20/20 [09:29<00:00, 28.61s/it, best=6.87, patience=6, val=6.87]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=35.13, patience=6, val=35.13]

Epochs:   5%|▌         | 1/20 [00:28<08:58, 28.35s/it, best=35.13, patience=6, val=35.13]

Epochs:   5%|▌         | 1/20 [00:56<08:58, 28.35s/it, best=21.77, patience=6, val=21.77]

Epochs:  10%|█         | 2/20 [00:56<08:33, 28.52s/it, best=21.77, patience=6, val=21.77]

Epochs:  10%|█         | 2/20 [01:25<08:33, 28.52s/it, best=17.51, patience=6, val=17.51]

Epochs:  15%|█▌        | 3/20 [01:25<08:06, 28.64s/it, best=17.51, patience=6, val=17.51]

Epochs:  15%|█▌        | 3/20 [01:53<08:06, 28.64s/it, best=16.21, patience=6, val=16.21]

Epochs:  20%|██        | 4/20 [01:53<07:33, 28.37s/it, best=16.21, patience=6, val=16.21]

Epochs:  20%|██        | 4/20 [02:21<07:33, 28.37s/it, best=14.37, patience=6, val=14.37]

Epochs:  25%|██▌       | 5/20 [02:21<07:04, 28.32s/it, best=14.37, patience=6, val=14.37]

Epochs:  25%|██▌       | 5/20 [02:50<07:04, 28.32s/it, best=12.63, patience=6, val=12.63]

Epochs:  30%|███       | 6/20 [02:50<06:36, 28.29s/it, best=12.63, patience=6, val=12.63]

Epochs:  30%|███       | 6/20 [03:18<06:36, 28.29s/it, best=10.87, patience=6, val=10.87]

Epochs:  35%|███▌      | 7/20 [03:18<06:07, 28.30s/it, best=10.87, patience=6, val=10.87]

Epochs:  35%|███▌      | 7/20 [03:46<06:07, 28.30s/it, best=10.11, patience=6, val=10.11]

Epochs:  40%|████      | 8/20 [03:46<05:40, 28.35s/it, best=10.11, patience=6, val=10.11]

Epochs:  40%|████      | 8/20 [04:15<05:40, 28.35s/it, best=8.44, patience=6, val=8.44]


Fold 1: MAE=8.284, RMSE=10.455, R2=0.7577469944953918, best={'head_lr': 0.001, 'backbone_lr': 1e-05, 'weight_decay': 0.0001}

Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=26.20, patience=6, val=26.20]

Epochs:   5%|▌         | 1/20 [00:28<09:03, 28.61s/it, best=26.20, patience=6, val=26.20]

Epochs:   5%|▌         | 1/20 [00:57<09:03, 28.61s/it, best=17.51, patience=6, val=17.51]

Epochs:  10%|█         | 2/20 [00:57<08:35, 28.66s/it, best=17.51, patience=6, val=17.51]

Epochs:  10%|█         | 2/20 [01:25<08:35, 28.66s/it, best=15.94, patience=6, val=15.94]

Epochs:  15%|█▌        | 3/20 [01:25<08:04, 28.51s/it, best=15.94, patience=6, val=15.94]

Epochs:  15%|█▌        | 3/20 [01:54<08:04, 28.51s/it, best=13.69, patience=6, val=13.69]

Epochs:  20%|██        | 4/20 [01:54<07:36, 28.55s/it, best=13.69, patience=6, val=13.69]

Epochs:  20%|██        | 4/20 [02:22<07:36, 28.55s/it, best=12.28, patience=6, val=12.28]

Epochs:  25%|██▌       | 5/20 [02:22<07:07, 28.50s/it, best=12.28, patience=6, val=12.28]

Epochs:  25%|██▌       | 5/20 [02:51<07:07, 28.50s/it, best=10.89, patience=6, val=10.89]

Epochs:  30%|███       | 6/20 [02:51<06:38, 28.50s/it, best=10.89, patience=6, val=10.89]

Epochs:  30%|███       | 6/20 [03:19<06:38, 28.50s/it, best=9.75, patience=6, val=9.75]

Epochs:  35%|███▌      | 7/20 [03:19<06:09, 28.42s/it, best=9.75, patience=6, val=9.75]

Epochs:  35%|███▌      | 7/20 [03:47<06:09, 28.42s/it, best=8.84, patience=6, val=8.84]

Epochs:  40%|████      | 8/20 [03:47<05:40, 28.41s/it, best=8.84, patience=6, val=8.84]

Epochs:  40%|████      | 8/20 [04:16<05:40, 28.41s/it, best=8.40, patience=6, val=8.40]

Epochs:  45%|████▌     | 9/20 [04:16<05:12, 28.41s/it, best=8.40, patience=6, val=8.40]

Epochs:  45%|████▌     | 9/20 [04:44<05:12, 28.41s/it, best=8.36, patience=6, val=8.36]

Epochs:  50%|█████     | 10/20 [04:44<04:43, 28.34s/it, best=8.36, patience=6, val=8.36]

Epochs:  50%|█████     | 10/20 [05:12<04:43, 28.34s/it, best=8.10, patience=6, val=8.10]

Epochs:  55%|█████▌    | 11/20 [05:12<04:15, 28.42s/it, best=8.10, patience=6, val=8.10]

Epochs:  55%|█████▌    | 11/20 [05:41<04:15, 28.42s/it, best=7.64, patience=6, val=7.64]

Epochs:  60%|██████    | 12/20 [05:41<03:47, 28.49s/it, best=7.64, patience=6, val=7.64]

Epochs:  60%|██████    | 12/20 [06:10<03:47, 28.49s/it, best=7.58, patience=6, val=7.58]

Epochs:  65%|██████▌   | 13/20 [06:10<03:19, 28.50s/it, best=7.58, patience=6, val=7.58]

Epochs:  65%|██████▌   | 13/20 [06:38<03:19, 28.50s/it, best=7.08, patience=6, val=7.08]

Epochs:  70%|███████   | 14/20 [06:38<02:50, 28.47s/it, best=7.08, patience=6, val=7.08]

Epochs:  70%|███████   | 14/20 [07:06<02:50, 28.47s/it, best=6.80, patience=6, val=6.80]

Epochs:  75%|███████▌  | 15/20 [07:06<02:22, 28.44s/it, best=6.80, patience=6, val=6.80]

Epochs:  75%|███████▌  | 15/20 [07:35<02:22, 28.44s/it, best=6.59, patience=6, val=6.59]

Epochs:  80%|████████  | 16/20 [07:35<01:53, 28.44s/it, best=6.59, patience=6, val=6.59]

Epochs:  80%|████████  | 16/20 [08:03<01:53, 28.44s/it, best=6.59, patience=5, val=6.74]

Epochs:  85%|████████▌ | 17/20 [08:03<01:25, 28.42s/it, best=6.59, patience=5, val=6.74]

Epochs:  85%|████████▌ | 17/20 [08:31<01:25, 28.42s/it, best=6.54, patience=6, val=6.54]

Epochs:  90%|█████████ | 18/20 [08:31<00:56, 28.37s/it, best=6.54, patience=6, val=6.54]

Epochs:  90%|█████████ | 18/20 [09:00<00:56, 28.37s/it, best=6.54, patience=5, val=6.99]

Epochs:  95%|█████████▌| 19/20 [09:00<00:28, 28.41s/it, best=6.54, patience=5, val=6.99]

Epochs:  95%|█████████▌| 19/20 [09:28<00:28, 28.41s/it, best=6.43, patience=6, val=6.43]

Epochs: 100%|██████████| 20/20 [09:28<00:00, 28.41s/it, best=6.43, patience=6, val=6.43]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:29<?, ?it/s, best=25.69, patience=6, val=25.69]

Epochs:   5%|▌         | 1/20 [00:29<09:11, 29.00s/it, best=25.69, patience=6, val=25.69]

Epochs:   5%|▌         | 1/20 [00:58<09:11, 29.00s/it, best=16.90, patience=6, val=16.90]

Epochs:  10%|█         | 2/20 [00:58<08:44, 29.13s/it, best=16.90, patience=6, val=16.90]

Epochs:  10%|█         | 2/20 [01:26<08:44, 29.13s/it, best=15.34, patience=6, val=15.34]

Epochs:  15%|█▌        | 3/20 [01:26<08:10, 28.83s/it, best=15.34, patience=6, val=15.34]

Epochs:  15%|█▌        | 3/20 [01:55<08:10, 28.83s/it, best=12.48, patience=6, val=12.48]

Epochs:  20%|██        | 4/20 [01:55<07:38, 28.64s/it, best=12.48, patience=6, val=12.48]

Epochs:  20%|██        | 4/20 [02:23<07:38, 28.64s/it, best=10.71, patience=6, val=10.71]

Epochs:  25%|██▌       | 5/20 [02:23<07:09, 28.64s/it, best=10.71, patience=6, val=10.71]

Epochs:  25%|██▌       | 5/20 [02:51<07:09, 28.64s/it, best=9.28, patience=6, val=9.28]

Epochs:  30%|███       | 6/20 [02:51<06:38, 28.49s/it, best=9.28, patience=6, val=9.28]

Epochs:  30%|███       | 6/20 [03:20<06:38, 28.49s/it, best=8.39, patience=6, val=8.39]

Epochs:  35%|███▌      | 7/20 [03:20<06:09, 28.44s/it, best=8.39, patience=6, val=8.39]

Epochs:  35%|███▌      | 7/20 [03:48<06:09, 28.44s/it, best=8.08, patience=6, val=8.08]

Epochs:  40%|████      | 8/20 [03:48<05:40, 28.36s/it, best=8.08, patience=6, val=8.08]

Epochs:  40%|████      | 8/20 [04:16<05:40, 28.36s/it, best=7.80, patience=6, val=7.80]

Epochs:  45%|████▌     | 9/20 [04:16<05:11, 28.31s/it, best=7.80, patience=6, val=7.80]

Epochs:  45%|████▌     | 9/20 [04:45<05:11, 28.31s/it, best=7.80, patience=5, val=7.86]

Epochs:  50%|█████     | 10/20 [04:45<04:43, 28.34s/it, best=7.80, patience=5, val=7.86]

Epochs:  50%|█████     | 10/20 [05:13<04:43, 28.34s/it, best=7.80, patience=4, val=8.03]

Epochs:  55%|█████▌    | 11/20 [05:13<04:14, 28.31s/it, best=7.80, patience=4, val=8.03]

Epochs:  55%|█████▌    | 11/20 [05:41<04:14, 28.31s/it, best=7.66, patience=6, val=7.66]

Epochs:  60%|██████    | 12/20 [05:41<03:47, 28.38s/it, best=7.66, patience=6, val=7.66]

Epochs:  60%|██████    | 12/20 [06:10<03:47, 28.38s/it, best=7.66, patience=5, val=7.78]

Epochs:  65%|██████▌   | 13/20 [06:10<03:19, 28.49s/it, best=7.66, patience=5, val=7.78]

Epochs:  65%|██████▌   | 13/20 [06:39<03:19, 28.49s/it, best=7.66, patience=4, val=7.67]

Epochs:  70%|███████   | 14/20 [06:39<02:51, 28.53s/it, best=7.66, patience=4, val=7.67]

Epochs:  70%|███████   | 14/20 [07:07<02:51, 28.53s/it, best=7.55, patience=6, val=7.55]

Epochs:  75%|███████▌  | 15/20 [07:07<02:22, 28.56s/it, best=7.55, patience=6, val=7.55]

Epochs:  75%|███████▌  | 15/20 [07:35<02:22, 28.56s/it, best=7.53, patience=6, val=7.53]

Epochs:  80%|████████  | 16/20 [07:35<01:53, 28.45s/it, best=7.53, patience=6, val=7.53]

Epochs:  80%|████████  | 16/20 [08:04<01:53, 28.45s/it, best=7.53, patience=5, val=7.62]

Epochs:  85%|████████▌ | 17/20 [08:04<01:25, 28.43s/it, best=7.53, patience=5, val=7.62]

Epochs:  85%|████████▌ | 17/20 [08:32<01:25, 28.43s/it, best=7.53, patience=4, val=7.75]

Epochs:  90%|█████████ | 18/20 [08:32<00:56, 28.41s/it, best=7.53, patience=4, val=7.75]

Epochs:  90%|█████████ | 18/20 [09:01<00:56, 28.41s/it, best=7.53, patience=3, val=8.11]

Epochs:  95%|█████████▌| 19/20 [09:01<00:28, 28.40s/it, best=7.53, patience=3, val=8.11]

Epochs:  95%|█████████▌| 19/20 [09:29<00:28, 28.40s/it, best=7.53, patience=2, val=7.99]

Epochs: 100%|██████████| 20/20 [09:29<00:00, 28.46s/it, best=7.53, patience=2, val=7.99]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=24.59, patience=6, val=24.59]

Epochs:   5%|▌         | 1/20 [00:28<09:01, 28.49s/it, best=24.59, patience=6, val=24.59]

Epochs:   5%|▌         | 1/20 [00:57<09:01, 28.49s/it, best=16.76, patience=6, val=16.76]

Epochs:  10%|█         | 2/20 [00:57<08:35, 28.66s/it, best=16.76, patience=6, val=16.76]

Epochs:  10%|█         | 2/20 [01:26<08:35, 28.66s/it, best=16.37, patience=6, val=16.37]

Epochs:  15%|█▌        | 3/20 [01:26<08:08, 28.72s/it, best=16.37, patience=6, val=16.37]

Epochs:  15%|█▌        | 3/20 [01:54<08:08, 28.72s/it, best=12.47, patience=6, val=12.47]

Epochs:  20%|██        | 4/20 [01:54<07:40, 28.75s/it, best=12.47, patience=6, val=12.47]

Epochs:  20%|██        | 4/20 [02:22<07:40, 28.75s/it, best=10.28, patience=6, val=10.28]

Epochs:  25%|██▌       | 5/20 [02:22<07:07, 28.50s/it, best=10.28, patience=6, val=10.28]

Epochs:  25%|██▌       | 5/20 [02:51<07:07, 28.50s/it, best=10.09, patience=6, val=10.09]

Epochs:  30%|███       | 6/20 [02:51<06:40, 28.62s/it, best=10.09, patience=6, val=10.09]

Epochs:  30%|███       | 6/20 [03:19<06:40, 28.62s/it, best=9.49, patience=6, val=9.49]

Epochs:  35%|███▌      | 7/20 [03:19<06:10, 28.49s/it, best=9.49, patience=6, val=9.49]

Epochs:  35%|███▌      | 7/20 [03:48<06:10, 28.49s/it, best=8.06, patience=6, val=8.06]

Epochs:  40%|████      | 8/20 [03:48<05:42, 28.55s/it, best=8.06, patience=6, val=8.06]

Epochs:  40%|████      | 8/20 [04:16<05:42, 28.55s/it, best=8.06, patience=5, val=8.26]

Epochs:  45%|████▌     | 9/20 [04:16<05:13, 28.48s/it, best=8.06, patience=5, val=8.26]

Epochs:  45%|████▌     | 9/20 [04:45<05:13, 28.48s/it, best=7.42, patience=6, val=7.42]

Epochs:  50%|█████     | 10/20 [04:45<04:44, 28.40s/it, best=7.42, patience=6, val=7.42]

Epochs:  50%|█████     | 10/20 [05:14<04:44, 28.40s/it, best=7.07, patience=6, val=7.07]

Epochs:  55%|█████▌    | 11/20 [05:14<04:16, 28.53s/it, best=7.07, patience=6, val=7.07]

Epochs:  55%|█████▌    | 11/20 [05:42<04:16, 28.53s/it, best=7.07, patience=5, val=7.83]

Epochs:  60%|██████    | 12/20 [05:42<03:47, 28.40s/it, best=7.07, patience=5, val=7.83]

Epochs:  60%|██████    | 12/20 [06:10<03:47, 28.40s/it, best=7.05, patience=6, val=7.05]

Epochs:  65%|██████▌   | 13/20 [06:10<03:18, 28.35s/it, best=7.05, patience=6, val=7.05]

Epochs:  65%|██████▌   | 13/20 [06:39<03:18, 28.35s/it, best=7.05, patience=5, val=7.44]

Epochs:  70%|███████   | 14/20 [06:39<02:50, 28.48s/it, best=7.05, patience=5, val=7.44]

Epochs:  70%|███████   | 14/20 [07:08<02:50, 28.48s/it, best=7.05, patience=4, val=7.48]

Epochs:  75%|███████▌  | 15/20 [07:08<02:23, 28.63s/it, best=7.05, patience=4, val=7.48]

Epochs:  75%|███████▌  | 15/20 [07:36<02:23, 28.63s/it, best=7.05, patience=3, val=7.72]

Epochs:  80%|████████  | 16/20 [07:36<01:54, 28.64s/it, best=7.05, patience=3, val=7.72]

Epochs:  80%|████████  | 16/20 [08:05<01:54, 28.64s/it, best=7.05, patience=2, val=7.45]

Epochs:  85%|████████▌ | 17/20 [08:05<01:26, 28.68s/it, best=7.05, patience=2, val=7.45]

Epochs:  85%|████████▌ | 17/20 [08:34<01:26, 28.68s/it, best=7.05, patience=1, val=7.61]

Epochs:  90%|█████████ | 18/20 [08:34<00:57, 28.69s/it, best=7.05, patience=1, val=7.61]

Epochs:  90%|█████████ | 18/20 [09:03<00:57, 28.69s/it, best=7.05, patience=0, val=7.42]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=27.58, patience=6, val=27.58]

Epochs:   5%|▌         | 1/20 [00:28<09:04, 28.68s/it, best=27.58, patience=6, val=27.58]

Epochs:   5%|▌         | 1/20 [00:57<09:04, 28.68s/it, best=16.31, patience=6, val=16.31]

Epochs:  10%|█         | 2/20 [00:57<08:38, 28.78s/it, best=16.31, patience=6, val=16.31]

Epochs:  10%|█         | 2/20 [01:26<08:38, 28.78s/it, best=14.53, patience=6, val=14.53]

Epochs:  15%|█▌        | 3/20 [01:26<08:08, 28.72s/it, best=14.53, patience=6, val=14.53]

Epochs:  15%|█▌        | 3/20 [01:55<08:08, 28.72s/it, best=13.09, patience=6, val=13.09]

Epochs:  20%|██        | 4/20 [01:55<07:41, 28.85s/it, best=13.09, patience=6, val=13.09]

Epochs:  20%|██        | 4/20 [02:24<07:41, 28.85s/it, best=12.07, patience=6, val=12.07]

Epochs:  25%|██▌       | 5/20 [02:24<07:12, 28.84s/it, best=12.07, patience=6, val=12.07]

Epochs:  25%|██▌       | 5/20 [02:52<07:12, 28.84s/it, best=10.40, patience=6, val=10.40]

Epochs:  30%|███       | 6/20 [02:52<06:40, 28.61s/it, best=10.40, patience=6, val=10.40]

Epochs:  30%|███       | 6/20 [03:20<06:40, 28.61s/it, best=10.35, patience=6, val=10.35]

Epochs:  35%|███▌      | 7/20 [03:20<06:10, 28.54s/it, best=10.35, patience=6, val=10.35]

Epochs:  35%|███▌      | 7/20 [03:49<06:10, 28.54s/it, best=10.04, patience=6, val=10.04]

Epochs:  40%|████      | 8/20 [03:49<05:42, 28.50s/it, best=10.04, patience=6, val=10.04]

Epochs:  40%|████      | 8/20 [04:17<05:42, 28.50s/it, best=9.85, patience=6, val=9.85]

Epochs:  45%|████▌     | 9/20 [04:17<05:12, 28.45s/it, best=9.85, patience=6, val=9.85]

Epochs:  45%|████▌     | 9/20 [04:45<05:12, 28.45s/it, best=9.30, patience=6, val=9.30]

Epochs:  50%|█████     | 10/20 [04:45<04:44, 28.43s/it, best=9.30, patience=6, val=9.30]

Epochs:  50%|█████     | 10/20 [05:14<04:44, 28.43s/it, best=9.30, patience=5, val=10.37]

Epochs:  55%|█████▌    | 11/20 [05:14<04:15, 28.44s/it, best=9.30, patience=5, val=10.37]

Epochs:  55%|█████▌    | 11/20 [05:42<04:15, 28.44s/it, best=8.47, patience=6, val=8.47]

Epochs:  60%|██████    | 12/20 [05:42<03:47, 28.48s/it, best=8.47, patience=6, val=8.47]

Epochs:  60%|██████    | 12/20 [06:11<03:47, 28.48s/it, best=8.47, patience=5, val=9.31]

Epochs:  65%|██████▌   | 13/20 [06:11<03:19, 28.44s/it, best=8.47, patience=5, val=9.31]

Epochs:  65%|██████▌   | 13/20 [06:39<03:19, 28.44s/it, best=8.43, patience=6, val=8.43]

Epochs:  70%|███████   | 14/20 [06:39<02:50, 28.43s/it, best=8.43, patience=6, val=8.43]

Epochs:  70%|███████   | 14/20 [07:07<02:50, 28.43s/it, best=8.43, patience=5, val=8.81]

Epochs:  75%|███████▌  | 15/20 [07:07<02:22, 28.43s/it, best=8.43, patience=5, val=8.81]

Epochs:  75%|███████▌  | 15/20 [07:36<02:22, 28.43s/it, best=7.81, patience=6, val=7.81]

Epochs:  80%|████████  | 16/20 [07:36<01:53, 28.42s/it, best=7.81, patience=6, val=7.81]

Epochs:  80%|████████  | 16/20 [08:04<01:53, 28.42s/it, best=7.81, patience=5, val=7.91]

Epochs:  85%|████████▌ | 17/20 [08:04<01:25, 28.45s/it, best=7.81, patience=5, val=7.91]

Epochs:  85%|████████▌ | 17/20 [08:33<01:25, 28.45s/it, best=7.56, patience=6, val=7.56]

Epochs:  90%|█████████ | 18/20 [08:33<00:56, 28.49s/it, best=7.56, patience=6, val=7.56]

Epochs:  90%|█████████ | 18/20 [09:02<00:56, 28.49s/it, best=7.56, patience=5, val=8.07]

Epochs:  95%|█████████▌| 19/20 [09:02<00:28, 28.52s/it, best=7.56, patience=5, val=8.07]

Epochs:  95%|█████████▌| 19/20 [09:30<00:28, 28.52s/it, best=7.52, patience=6, val=7.52]

Epochs: 100%|██████████| 20/20 [09:30<00:00, 28.49s/it, best=7.52, patience=6, val=7.52]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:29<?, ?it/s, best=25.64, patience=6, val=25.64]

Epochs:   5%|▌         | 1/20 [00:29<09:12, 29.09s/it, best=25.64, patience=6, val=25.64]

Epochs:   5%|▌         | 1/20 [00:58<09:12, 29.09s/it, best=16.41, patience=6, val=16.41]

Epochs:  10%|█         | 2/20 [00:58<08:44, 29.12s/it, best=16.41, patience=6, val=16.41]

Epochs:  10%|█         | 2/20 [01:27<08:44, 29.12s/it, best=14.28, patience=6, val=14.28]

Epochs:  15%|█▌        | 3/20 [01:27<08:14, 29.12s/it, best=14.28, patience=6, val=14.28]

Epochs:  15%|█▌        | 3/20 [01:56<08:14, 29.12s/it, best=11.80, patience=6, val=11.80]

Epochs:  20%|██        | 4/20 [01:56<07:43, 28.95s/it, best=11.80, patience=6, val=11.80]

Epochs:  20%|██        | 4/20 [02:24<07:43, 28.95s/it, best=10.39, patience=6, val=10.39]

Epochs:  25%|██▌       | 5/20 [02:24<07:12, 28.85s/it, best=10.39, patience=6, val=10.39]

Epochs:  25%|██▌       | 5/20 [02:53<07:12, 28.85s/it, best=8.43, patience=6, val=8.43]

Epochs:  30%|███       | 6/20 [02:53<06:41, 28.69s/it, best=8.43, patience=6, val=8.43]

Epochs:  30%|███       | 6/20 [03:21<06:41, 28.69s/it, best=7.50, patience=6, val=7.50]

Epochs:  35%|███▌      | 7/20 [03:21<06:13, 28.73s/it, best=7.50, patience=6, val=7.50]

Epochs:  35%|███▌      | 7/20 [03:50<06:13, 28.73s/it, best=7.50, patience=5, val=8.04]

Epochs:  40%|████      | 8/20 [03:50<05:44, 28.70s/it, best=7.50, patience=5, val=8.04]

Epochs:  40%|████      | 8/20 [04:19<05:44, 28.70s/it, best=7.50, patience=4, val=7.61]

Epochs:  45%|████▌     | 9/20 [04:19<05:15, 28.65s/it, best=7.50, patience=4, val=7.61]

Epochs:  45%|████▌     | 9/20 [04:47<05:15, 28.65s/it, best=7.50, patience=3, val=7.74]

Epochs:  50%|█████     | 10/20 [04:47<04:45, 28.52s/it, best=7.50, patience=3, val=7.74]

Epochs:  50%|█████     | 10/20 [05:15<04:45, 28.52s/it, best=7.50, patience=2, val=8.37]

Epochs:  55%|█████▌    | 11/20 [05:15<04:16, 28.47s/it, best=7.50, patience=2, val=8.37]

Epochs:  55%|█████▌    | 11/20 [05:45<04:16, 28.47s/it, best=6.76, patience=6, val=6.76]

Epochs:  60%|██████    | 12/20 [05:45<03:51, 28.91s/it, best=6.76, patience=6, val=6.76]

Epochs:  60%|██████    | 12/20 [06:15<03:51, 28.91s/it, best=6.76, patience=5, val=7.70]

Epochs:  65%|██████▌   | 13/20 [06:15<03:25, 29.32s/it, best=6.76, patience=5, val=7.70]

Epochs:  65%|██████▌   | 13/20 [06:44<03:25, 29.32s/it, best=6.76, patience=4, val=7.12]

Epochs:  70%|███████   | 14/20 [06:44<02:54, 29.14s/it, best=6.76, patience=4, val=7.12]

Epochs:  70%|███████   | 14/20 [07:13<02:54, 29.14s/it, best=6.76, patience=3, val=6.84]

Epochs:  75%|███████▌  | 15/20 [07:13<02:24, 28.93s/it, best=6.76, patience=3, val=6.84]

Epochs:  75%|███████▌  | 15/20 [07:41<02:24, 28.93s/it, best=6.76, patience=2, val=7.60]

Epochs:  80%|████████  | 16/20 [07:41<01:55, 28.86s/it, best=6.76, patience=2, val=7.60]

Epochs:  80%|████████  | 16/20 [08:10<01:55, 28.86s/it, best=6.76, patience=1, val=7.23]

Epochs:  85%|████████▌ | 17/20 [08:10<01:26, 28.89s/it, best=6.76, patience=1, val=7.23]

Epochs:  85%|████████▌ | 17/20 [08:39<01:26, 28.89s/it, best=6.76, patience=0, val=7.14]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=26.33, patience=6, val=26.33]

Epochs:   5%|▌         | 1/20 [00:28<09:08, 28.85s/it, best=26.33, patience=6, val=26.33]

Epochs:   5%|▌         | 1/20 [00:57<09:08, 28.85s/it, best=16.91, patience=6, val=16.91]

Epochs:  10%|█         | 2/20 [00:57<08:35, 28.66s/it, best=16.91, patience=6, val=16.91]

Epochs:  10%|█         | 2/20 [01:25<08:35, 28.66s/it, best=15.26, patience=6, val=15.26]

Epochs:  15%|█▌        | 3/20 [01:25<08:06, 28.63s/it, best=15.26, patience=6, val=15.26]

Epochs:  15%|█▌        | 3/20 [01:54<08:06, 28.63s/it, best=12.95, patience=6, val=12.95]

Epochs:  20%|██        | 4/20 [01:54<07:36, 28.53s/it, best=12.95, patience=6, val=12.95]

Epochs:  20%|██        | 4/20 [02:23<07:36, 28.53s/it, best=11.06, patience=6, val=11.06]

Epochs:  25%|██▌       | 5/20 [02:23<07:09, 28.65s/it, best=11.06, patience=6, val=11.06]

Epochs:  25%|██▌       | 5/20 [02:51<07:09, 28.65s/it, best=10.10, patience=6, val=10.10]

Epochs:  30%|███       | 6/20 [02:51<06:40, 28.61s/it, best=10.10, patience=6, val=10.10]

Epochs:  30%|███       | 6/20 [03:20<06:40, 28.61s/it, best=8.89, patience=6, val=8.89]

Epochs:  35%|███▌      | 7/20 [03:20<06:11, 28.57s/it, best=8.89, patience=6, val=8.89]

Epochs:  35%|███▌      | 7/20 [03:48<06:11, 28.57s/it, best=8.34, patience=6, val=8.34]

Epochs:  40%|████      | 8/20 [03:48<05:40, 28.38s/it, best=8.34, patience=6, val=8.34]

Epochs:  40%|████      | 8/20 [04:16<05:40, 28.38s/it, best=7.85, patience=6, val=7.85]

Epochs:  45%|████▌     | 9/20 [04:16<05:11, 28.29s/it, best=7.85, patience=6, val=7.85]

Epochs:  45%|████▌     | 9/20 [04:44<05:11, 28.29s/it, best=7.53, patience=6, val=7.53]

Epochs:  50%|█████     | 10/20 [04:44<04:44, 28.40s/it, best=7.53, patience=6, val=7.53]

Epochs:  50%|█████     | 10/20 [05:13<04:44, 28.40s/it, best=7.53, patience=5, val=7.54]

Epochs:  55%|█████▌    | 11/20 [05:13<04:16, 28.52s/it, best=7.53, patience=5, val=7.54]

Epochs:  55%|█████▌    | 11/20 [05:42<04:16, 28.52s/it, best=7.13, patience=6, val=7.13]

Epochs:  60%|██████    | 12/20 [05:42<03:48, 28.60s/it, best=7.13, patience=6, val=7.13]

Epochs:  60%|██████    | 12/20 [06:11<03:48, 28.60s/it, best=6.73, patience=6, val=6.73]

Epochs:  65%|██████▌   | 13/20 [06:11<03:20, 28.60s/it, best=6.73, patience=6, val=6.73]

Epochs:  65%|██████▌   | 13/20 [06:39<03:20, 28.60s/it, best=6.34, patience=6, val=6.34]


Fold 2: MAE=8.622, RMSE=11.449, R2=0.7095177173614502, best={'head_lr': 0.001, 'backbone_lr': 1e-05, 'weight_decay': 0.0001}

Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:27<?, ?it/s, best=33.14, patience=6, val=33.14]

Epochs:   5%|▌         | 1/20 [00:27<08:35, 27.15s/it, best=33.14, patience=6, val=33.14]

Epochs:   5%|▌         | 1/20 [00:55<08:35, 27.15s/it, best=19.70, patience=6, val=19.70]

Epochs:  10%|█         | 2/20 [00:55<08:16, 27.60s/it, best=19.70, patience=6, val=19.70]

Epochs:  10%|█         | 2/20 [01:22<08:16, 27.60s/it, best=17.01, patience=6, val=17.01]

Epochs:  15%|█▌        | 3/20 [01:22<07:45, 27.41s/it, best=17.01, patience=6, val=17.01]

Epochs:  15%|█▌        | 3/20 [01:51<07:45, 27.41s/it, best=15.37, patience=6, val=15.37]

Epochs:  20%|██        | 4/20 [01:51<07:31, 28.24s/it, best=15.37, patience=6, val=15.37]

Epochs:  20%|██        | 4/20 [02:20<07:31, 28.24s/it, best=13.70, patience=6, val=13.70]

Epochs:  25%|██▌       | 5/20 [02:20<07:04, 28.28s/it, best=13.70, patience=6, val=13.70]

Epochs:  25%|██▌       | 5/20 [02:48<07:04, 28.28s/it, best=12.20, patience=6, val=12.20]

Epochs:  30%|███       | 6/20 [02:48<06:34, 28.18s/it, best=12.20, patience=6, val=12.20]

Epochs:  30%|███       | 6/20 [03:16<06:34, 28.18s/it, best=10.94, patience=6, val=10.94]

Epochs:  35%|███▌      | 7/20 [03:16<06:05, 28.11s/it, best=10.94, patience=6, val=10.94]

Epochs:  35%|███▌      | 7/20 [03:44<06:05, 28.11s/it, best=9.64, patience=6, val=9.64]

Epochs:  40%|████      | 8/20 [03:44<05:36, 28.06s/it, best=9.64, patience=6, val=9.64]

Epochs:  40%|████      | 8/20 [04:12<05:36, 28.06s/it, best=9.37, patience=6, val=9.37]

Epochs:  45%|████▌     | 9/20 [04:12<05:08, 28.04s/it, best=9.37, patience=6, val=9.37]

Epochs:  45%|████▌     | 9/20 [04:39<05:08, 28.04s/it, best=9.06, patience=6, val=9.06]

Epochs:  50%|█████     | 10/20 [04:39<04:38, 27.90s/it, best=9.06, patience=6, val=9.06]

Epochs:  50%|█████     | 10/20 [05:07<04:38, 27.90s/it, best=8.86, patience=6, val=8.86]

Epochs:  55%|█████▌    | 11/20 [05:07<04:10, 27.85s/it, best=8.86, patience=6, val=8.86]

Epochs:  55%|█████▌    | 11/20 [05:35<04:10, 27.85s/it, best=8.69, patience=6, val=8.69]

Epochs:  60%|██████    | 12/20 [05:35<03:42, 27.80s/it, best=8.69, patience=6, val=8.69]

Epochs:  60%|██████    | 12/20 [06:02<03:42, 27.80s/it, best=8.67, patience=6, val=8.67]

Epochs:  65%|██████▌   | 13/20 [06:02<03:14, 27.79s/it, best=8.67, patience=6, val=8.67]

Epochs:  65%|██████▌   | 13/20 [06:30<03:14, 27.79s/it, best=8.60, patience=6, val=8.60]

Epochs:  70%|███████   | 14/20 [06:30<02:46, 27.73s/it, best=8.60, patience=6, val=8.60]

Epochs:  70%|███████   | 14/20 [06:58<02:46, 27.73s/it, best=8.60, patience=5, val=8.62]

Epochs:  75%|███████▌  | 15/20 [06:58<02:18, 27.72s/it, best=8.60, patience=5, val=8.62]

Epochs:  75%|███████▌  | 15/20 [07:26<02:18, 27.72s/it, best=8.51, patience=6, val=8.51]

Epochs:  80%|████████  | 16/20 [07:26<01:51, 27.84s/it, best=8.51, patience=6, val=8.51]

Epochs:  80%|████████  | 16/20 [07:54<01:51, 27.84s/it, best=8.51, patience=5, val=8.64]

Epochs:  85%|████████▌ | 17/20 [07:54<01:23, 27.89s/it, best=8.51, patience=5, val=8.64]

Epochs:  85%|████████▌ | 17/20 [08:22<01:23, 27.89s/it, best=8.50, patience=6, val=8.50]

Epochs:  90%|█████████ | 18/20 [08:22<00:55, 27.97s/it, best=8.50, patience=6, val=8.50]

Epochs:  90%|█████████ | 18/20 [08:50<00:55, 27.97s/it, best=8.50, patience=5, val=8.58]

Epochs:  95%|█████████▌| 19/20 [08:50<00:27, 27.94s/it, best=8.50, patience=5, val=8.58]

Epochs:  95%|█████████▌| 19/20 [09:18<00:27, 27.94s/it, best=8.11, patience=6, val=8.11]

Epochs: 100%|██████████| 20/20 [09:18<00:00, 27.93s/it, best=8.11, patience=6, val=8.11]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=33.76, patience=6, val=33.76]

Epochs:   5%|▌         | 1/20 [00:28<08:52, 28.02s/it, best=33.76, patience=6, val=33.76]

Epochs:   5%|▌         | 1/20 [00:56<08:52, 28.02s/it, best=19.71, patience=6, val=19.71]

Epochs:  10%|█         | 2/20 [00:56<08:24, 28.02s/it, best=19.71, patience=6, val=19.71]

Epochs:  10%|█         | 2/20 [01:23<08:24, 28.02s/it, best=16.19, patience=6, val=16.19]

Epochs:  15%|█▌        | 3/20 [01:23<07:53, 27.84s/it, best=16.19, patience=6, val=16.19]

Epochs:  15%|█▌        | 3/20 [01:51<07:53, 27.84s/it, best=14.39, patience=6, val=14.39]

Epochs:  20%|██        | 4/20 [01:51<07:25, 27.83s/it, best=14.39, patience=6, val=14.39]

Epochs:  20%|██        | 4/20 [02:20<07:25, 27.83s/it, best=12.88, patience=6, val=12.88]

Epochs:  25%|██▌       | 5/20 [02:20<07:01, 28.09s/it, best=12.88, patience=6, val=12.88]

Epochs:  25%|██▌       | 5/20 [02:51<07:01, 28.09s/it, best=11.13, patience=6, val=11.13]

Epochs:  30%|███       | 6/20 [02:51<06:48, 29.21s/it, best=11.13, patience=6, val=11.13]

Epochs:  30%|███       | 6/20 [03:18<06:48, 29.21s/it, best=9.30, patience=6, val=9.30]

Epochs:  35%|███▌      | 7/20 [03:18<06:12, 28.64s/it, best=9.30, patience=6, val=9.30]

Epochs:  35%|███▌      | 7/20 [03:48<06:12, 28.64s/it, best=7.94, patience=6, val=7.94]

Epochs:  40%|████      | 8/20 [03:48<05:46, 28.88s/it, best=7.94, patience=6, val=7.94]

Epochs:  40%|████      | 8/20 [04:15<05:46, 28.88s/it, best=7.09, patience=6, val=7.09]

Epochs:  45%|████▌     | 9/20 [04:15<05:13, 28.48s/it, best=7.09, patience=6, val=7.09]

Epochs:  45%|████▌     | 9/20 [04:43<05:13, 28.48s/it, best=6.74, patience=6, val=6.74]

Epochs:  50%|█████     | 10/20 [04:43<04:43, 28.31s/it, best=6.74, patience=6, val=6.74]

Epochs:  50%|█████     | 10/20 [05:11<04:43, 28.31s/it, best=6.74, patience=5, val=7.20]

Epochs:  55%|█████▌    | 11/20 [05:11<04:13, 28.21s/it, best=6.74, patience=5, val=7.20]

Epochs:  55%|█████▌    | 11/20 [05:39<04:13, 28.21s/it, best=6.51, patience=6, val=6.51]

Epochs:  60%|██████    | 12/20 [05:39<03:45, 28.19s/it, best=6.51, patience=6, val=6.51]

Epochs:  60%|██████    | 12/20 [06:08<03:45, 28.19s/it, best=6.51, patience=5, val=6.87]

Epochs:  65%|██████▌   | 13/20 [06:08<03:17, 28.21s/it, best=6.51, patience=5, val=6.87]

Epochs:  65%|██████▌   | 13/20 [06:39<03:17, 28.21s/it, best=6.51, patience=4, val=7.11]

Epochs:  70%|███████   | 14/20 [06:39<02:54, 29.15s/it, best=6.51, patience=4, val=7.11]

Epochs:  70%|███████   | 14/20 [07:10<02:54, 29.15s/it, best=6.51, patience=3, val=7.48]

Epochs:  75%|███████▌  | 15/20 [07:10<02:28, 29.79s/it, best=6.51, patience=3, val=7.48]

Epochs:  75%|███████▌  | 15/20 [07:41<02:28, 29.79s/it, best=6.51, patience=2, val=6.96]

Epochs:  80%|████████  | 16/20 [07:41<02:00, 30.21s/it, best=6.51, patience=2, val=6.96]

Epochs:  80%|████████  | 16/20 [08:10<02:00, 30.21s/it, best=6.51, patience=1, val=7.51]

Epochs:  85%|████████▌ | 17/20 [08:10<01:28, 29.58s/it, best=6.51, patience=1, val=7.51]

Epochs:  85%|████████▌ | 17/20 [08:37<01:28, 29.58s/it, best=6.51, patience=0, val=6.73]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:27<?, ?it/s, best=32.21, patience=6, val=32.21]

Epochs:   5%|▌         | 1/20 [00:27<08:33, 27.01s/it, best=32.21, patience=6, val=32.21]

Epochs:   5%|▌         | 1/20 [00:54<08:33, 27.01s/it, best=18.82, patience=6, val=18.82]

Epochs:  10%|█         | 2/20 [00:54<08:11, 27.30s/it, best=18.82, patience=6, val=18.82]

Epochs:  10%|█         | 2/20 [01:21<08:11, 27.30s/it, best=16.59, patience=6, val=16.59]

Epochs:  15%|█▌        | 3/20 [01:21<07:44, 27.30s/it, best=16.59, patience=6, val=16.59]

Epochs:  15%|█▌        | 3/20 [01:49<07:44, 27.30s/it, best=14.97, patience=6, val=14.97]

Epochs:  20%|██        | 4/20 [01:49<07:18, 27.41s/it, best=14.97, patience=6, val=14.97]

Epochs:  20%|██        | 4/20 [02:16<07:18, 27.41s/it, best=12.66, patience=6, val=12.66]

Epochs:  25%|██▌       | 5/20 [02:16<06:51, 27.44s/it, best=12.66, patience=6, val=12.66]

Epochs:  25%|██▌       | 5/20 [02:44<06:51, 27.44s/it, best=11.13, patience=6, val=11.13]

Epochs:  30%|███       | 6/20 [02:44<06:26, 27.62s/it, best=11.13, patience=6, val=11.13]

Epochs:  30%|███       | 6/20 [03:13<06:26, 27.62s/it, best=9.94, patience=6, val=9.94]

Epochs:  35%|███▌      | 7/20 [03:13<06:01, 27.81s/it, best=9.94, patience=6, val=9.94]

Epochs:  35%|███▌      | 7/20 [03:41<06:01, 27.81s/it, best=9.07, patience=6, val=9.07]

Epochs:  40%|████      | 8/20 [03:41<05:35, 27.92s/it, best=9.07, patience=6, val=9.07]

Epochs:  40%|████      | 8/20 [04:09<05:35, 27.92s/it, best=8.28, patience=6, val=8.28]

Epochs:  45%|████▌     | 9/20 [04:09<05:07, 27.92s/it, best=8.28, patience=6, val=8.28]

Epochs:  45%|████▌     | 9/20 [04:37<05:07, 27.92s/it, best=7.86, patience=6, val=7.86]

Epochs:  50%|█████     | 10/20 [04:37<04:39, 27.99s/it, best=7.86, patience=6, val=7.86]

Epochs:  50%|█████     | 10/20 [05:05<04:39, 27.99s/it, best=7.20, patience=6, val=7.20]

Epochs:  55%|█████▌    | 11/20 [05:05<04:11, 27.96s/it, best=7.20, patience=6, val=7.20]

Epochs:  55%|█████▌    | 11/20 [05:33<04:11, 27.96s/it, best=7.20, patience=5, val=7.70]

Epochs:  60%|██████    | 12/20 [05:33<03:43, 27.98s/it, best=7.20, patience=5, val=7.70]

Epochs:  60%|██████    | 12/20 [06:02<03:43, 27.98s/it, best=7.03, patience=6, val=7.03]

Epochs:  65%|██████▌   | 13/20 [06:02<03:18, 28.40s/it, best=7.03, patience=6, val=7.03]

Epochs:  65%|██████▌   | 13/20 [06:34<03:18, 28.40s/it, best=7.03, patience=5, val=7.25]

Epochs:  70%|███████   | 14/20 [06:34<02:56, 29.35s/it, best=7.03, patience=5, val=7.25]

Epochs:  70%|███████   | 14/20 [07:03<02:56, 29.35s/it, best=6.53, patience=6, val=6.53]

Epochs:  75%|███████▌  | 15/20 [07:03<02:27, 29.45s/it, best=6.53, patience=6, val=6.53]

Epochs:  75%|███████▌  | 15/20 [07:31<02:27, 29.45s/it, best=6.53, patience=5, val=6.85]

Epochs:  80%|████████  | 16/20 [07:31<01:55, 28.84s/it, best=6.53, patience=5, val=6.85]

Epochs:  80%|████████  | 16/20 [07:58<01:55, 28.84s/it, best=6.21, patience=6, val=6.21]

Epochs:  85%|████████▌ | 17/20 [07:58<01:25, 28.45s/it, best=6.21, patience=6, val=6.21]

Epochs:  85%|████████▌ | 17/20 [08:26<01:25, 28.45s/it, best=6.21, patience=5, val=6.77]

Epochs:  90%|█████████ | 18/20 [08:26<00:56, 28.29s/it, best=6.21, patience=5, val=6.77]

Epochs:  90%|█████████ | 18/20 [08:54<00:56, 28.29s/it, best=6.21, patience=4, val=6.24]

Epochs:  95%|█████████▌| 19/20 [08:54<00:28, 28.22s/it, best=6.21, patience=4, val=6.24]

Epochs:  95%|█████████▌| 19/20 [09:22<00:28, 28.22s/it, best=6.21, patience=3, val=6.92]

Epochs: 100%|██████████| 20/20 [09:22<00:00, 28.15s/it, best=6.21, patience=3, val=6.92]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=31.37, patience=6, val=31.37]

Epochs:   5%|▌         | 1/20 [00:28<09:04, 28.68s/it, best=31.37, patience=6, val=31.37]

Epochs:   5%|▌         | 1/20 [00:57<09:04, 28.68s/it, best=17.94, patience=6, val=17.94]

Epochs:  10%|█         | 2/20 [00:57<08:37, 28.76s/it, best=17.94, patience=6, val=17.94]

Epochs:  10%|█         | 2/20 [01:26<08:37, 28.76s/it, best=17.12, patience=6, val=17.12]

Epochs:  15%|█▌        | 3/20 [01:26<08:07, 28.67s/it, best=17.12, patience=6, val=17.12]

Epochs:  15%|█▌        | 3/20 [01:54<08:07, 28.67s/it, best=14.54, patience=6, val=14.54]

Epochs:  20%|██        | 4/20 [01:54<07:37, 28.62s/it, best=14.54, patience=6, val=14.54]

Epochs:  20%|██        | 4/20 [02:22<07:37, 28.62s/it, best=13.06, patience=6, val=13.06]

Epochs:  25%|██▌       | 5/20 [02:22<07:07, 28.49s/it, best=13.06, patience=6, val=13.06]

Epochs:  25%|██▌       | 5/20 [02:51<07:07, 28.49s/it, best=12.01, patience=6, val=12.01]

Epochs:  30%|███       | 6/20 [02:51<06:41, 28.65s/it, best=12.01, patience=6, val=12.01]

Epochs:  30%|███       | 6/20 [03:23<06:41, 28.65s/it, best=11.65, patience=6, val=11.65]

Epochs:  35%|███▌      | 7/20 [03:23<06:26, 29.70s/it, best=11.65, patience=6, val=11.65]

Epochs:  35%|███▌      | 7/20 [03:54<06:26, 29.70s/it, best=10.65, patience=6, val=10.65]

Epochs:  40%|████      | 8/20 [03:54<06:02, 30.17s/it, best=10.65, patience=6, val=10.65]

Epochs:  40%|████      | 8/20 [04:23<06:02, 30.17s/it, best=10.51, patience=6, val=10.51]

Epochs:  45%|████▌     | 9/20 [04:23<05:26, 29.68s/it, best=10.51, patience=6, val=10.51]

Epochs:  45%|████▌     | 9/20 [04:50<05:26, 29.68s/it, best=9.85, patience=6, val=9.85]

Epochs:  50%|█████     | 10/20 [04:50<04:49, 28.96s/it, best=9.85, patience=6, val=9.85]

Epochs:  50%|█████     | 10/20 [05:21<04:49, 28.96s/it, best=9.77, patience=6, val=9.77]

Epochs:  55%|█████▌    | 11/20 [05:21<04:25, 29.46s/it, best=9.77, patience=6, val=9.77]

Epochs:  55%|█████▌    | 11/20 [05:49<04:25, 29.46s/it, best=9.75, patience=6, val=9.75]

Epochs:  60%|██████    | 12/20 [05:49<03:52, 29.07s/it, best=9.75, patience=6, val=9.75]

Epochs:  60%|██████    | 12/20 [06:17<03:52, 29.07s/it, best=9.24, patience=6, val=9.24]

Epochs:  65%|██████▌   | 13/20 [06:17<03:20, 28.68s/it, best=9.24, patience=6, val=9.24]

Epochs:  65%|██████▌   | 13/20 [06:45<03:20, 28.68s/it, best=9.24, patience=6, val=9.24]

Epochs:  70%|███████   | 14/20 [06:45<02:50, 28.48s/it, best=9.24, patience=6, val=9.24]

Epochs:  70%|███████   | 14/20 [07:13<02:50, 28.48s/it, best=8.77, patience=6, val=8.77]

Epochs:  75%|███████▌  | 15/20 [07:13<02:21, 28.37s/it, best=8.77, patience=6, val=8.77]

Epochs:  75%|███████▌  | 15/20 [07:41<02:21, 28.37s/it, best=8.72, patience=6, val=8.72]

Epochs:  80%|████████  | 16/20 [07:41<01:53, 28.34s/it, best=8.72, patience=6, val=8.72]

Epochs:  80%|████████  | 16/20 [08:09<01:53, 28.34s/it, best=8.42, patience=6, val=8.42]

Epochs:  85%|████████▌ | 17/20 [08:09<01:24, 28.19s/it, best=8.42, patience=6, val=8.42]

Epochs:  85%|████████▌ | 17/20 [08:37<01:24, 28.19s/it, best=8.23, patience=6, val=8.23]

Epochs:  90%|█████████ | 18/20 [08:37<00:56, 28.12s/it, best=8.23, patience=6, val=8.23]

Epochs:  90%|█████████ | 18/20 [09:05<00:56, 28.12s/it, best=8.23, patience=5, val=8.32]

Epochs:  95%|█████████▌| 19/20 [09:05<00:28, 28.18s/it, best=8.23, patience=5, val=8.32]

Epochs:  95%|█████████▌| 19/20 [09:33<00:28, 28.18s/it, best=8.06, patience=6, val=8.06]

Epochs: 100%|██████████| 20/20 [09:33<00:00, 28.14s/it, best=8.06, patience=6, val=8.06]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:30<?, ?it/s, best=32.43, patience=6, val=32.43]

Epochs:   5%|▌         | 1/20 [00:30<09:44, 30.78s/it, best=32.43, patience=6, val=32.43]

Epochs:   5%|▌         | 1/20 [01:02<09:44, 30.78s/it, best=18.46, patience=6, val=18.46]

Epochs:  10%|█         | 2/20 [01:02<09:27, 31.53s/it, best=18.46, patience=6, val=18.46]

Epochs:  10%|█         | 2/20 [01:34<09:27, 31.53s/it, best=15.65, patience=6, val=15.65]

Epochs:  15%|█▌        | 3/20 [01:34<08:58, 31.65s/it, best=15.65, patience=6, val=15.65]

Epochs:  15%|█▌        | 3/20 [02:04<08:58, 31.65s/it, best=13.76, patience=6, val=13.76]

Epochs:  20%|██        | 4/20 [02:04<08:16, 31.01s/it, best=13.76, patience=6, val=13.76]

Epochs:  20%|██        | 4/20 [02:32<08:16, 31.01s/it, best=13.76, patience=5, val=15.52]

Epochs:  25%|██▌       | 5/20 [02:32<07:26, 29.78s/it, best=13.76, patience=5, val=15.52]

Epochs:  25%|██▌       | 5/20 [02:59<07:26, 29.78s/it, best=13.27, patience=6, val=13.27]

Epochs:  30%|███       | 6/20 [02:59<06:47, 29.08s/it, best=13.27, patience=6, val=13.27]

Epochs:  30%|███       | 6/20 [03:28<06:47, 29.08s/it, best=12.64, patience=6, val=12.64]

Epochs:  35%|███▌      | 7/20 [03:28<06:13, 28.74s/it, best=12.64, patience=6, val=12.64]

Epochs:  35%|███▌      | 7/20 [03:57<06:13, 28.74s/it, best=12.64, patience=5, val=12.97]

Epochs:  40%|████      | 8/20 [03:57<05:48, 29.06s/it, best=12.64, patience=5, val=12.97]

Epochs:  40%|████      | 8/20 [04:25<05:48, 29.06s/it, best=11.86, patience=6, val=11.86]

Epochs:  45%|████▌     | 9/20 [04:25<05:13, 28.50s/it, best=11.86, patience=6, val=11.86]

Epochs:  45%|████▌     | 9/20 [04:53<05:13, 28.50s/it, best=11.86, patience=5, val=13.35]

Epochs:  50%|█████     | 10/20 [04:53<04:44, 28.45s/it, best=11.86, patience=5, val=13.35]

Epochs:  50%|█████     | 10/20 [05:20<04:44, 28.45s/it, best=11.86, patience=4, val=12.01]

Epochs:  55%|█████▌    | 11/20 [05:20<04:13, 28.18s/it, best=11.86, patience=4, val=12.01]

Epochs:  55%|█████▌    | 11/20 [05:48<04:13, 28.18s/it, best=11.41, patience=6, val=11.41]

Epochs:  60%|██████    | 12/20 [05:48<03:44, 28.09s/it, best=11.41, patience=6, val=11.41]

Epochs:  60%|██████    | 12/20 [06:17<03:44, 28.09s/it, best=11.41, patience=5, val=11.42]

Epochs:  65%|██████▌   | 13/20 [06:17<03:17, 28.23s/it, best=11.41, patience=5, val=11.42]

Epochs:  65%|██████▌   | 13/20 [06:45<03:17, 28.23s/it, best=11.16, patience=6, val=11.16]

Epochs:  70%|███████   | 14/20 [06:45<02:48, 28.15s/it, best=11.16, patience=6, val=11.16]

Epochs:  70%|███████   | 14/20 [07:13<02:48, 28.15s/it, best=11.16, patience=5, val=12.10]

Epochs:  75%|███████▌  | 15/20 [07:13<02:21, 28.24s/it, best=11.16, patience=5, val=12.10]

Epochs:  75%|███████▌  | 15/20 [07:43<02:21, 28.24s/it, best=10.96, patience=6, val=10.96]

Epochs:  80%|████████  | 16/20 [07:43<01:54, 28.58s/it, best=10.96, patience=6, val=10.96]

Epochs:  80%|████████  | 16/20 [08:15<01:54, 28.58s/it, best=10.68, patience=6, val=10.68]

Epochs:  85%|████████▌ | 17/20 [08:15<01:28, 29.63s/it, best=10.68, patience=6, val=10.68]

Epochs:  85%|████████▌ | 17/20 [08:47<01:28, 29.63s/it, best=10.68, patience=5, val=11.35]

Epochs:  90%|█████████ | 18/20 [08:47<01:00, 30.40s/it, best=10.68, patience=5, val=11.35]

Epochs:  90%|█████████ | 18/20 [09:18<01:00, 30.40s/it, best=9.99, patience=6, val=9.99]

Epochs:  95%|█████████▌| 19/20 [09:18<00:30, 30.73s/it, best=9.99, patience=6, val=9.99]

Epochs:  95%|█████████▌| 19/20 [09:48<00:30, 30.73s/it, best=9.99, patience=5, val=10.50]

Epochs: 100%|██████████| 20/20 [09:48<00:00, 30.31s/it, best=9.99, patience=5, val=10.50]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:26<?, ?it/s, best=33.22, patience=6, val=33.22]

Epochs:   5%|▌         | 1/20 [00:26<08:28, 26.77s/it, best=33.22, patience=6, val=33.22]

Epochs:   5%|▌         | 1/20 [00:53<08:28, 26.77s/it, best=19.61, patience=6, val=19.61]

Epochs:  10%|█         | 2/20 [00:53<08:05, 26.99s/it, best=19.61, patience=6, val=19.61]

Epochs:  10%|█         | 2/20 [01:21<08:05, 26.99s/it, best=16.92, patience=6, val=16.92]

Epochs:  15%|█▌        | 3/20 [01:21<07:45, 27.38s/it, best=16.92, patience=6, val=16.92]

Epochs:  15%|█▌        | 3/20 [01:49<07:45, 27.38s/it, best=15.08, patience=6, val=15.08]

Epochs:  20%|██        | 4/20 [01:49<07:20, 27.52s/it, best=15.08, patience=6, val=15.08]

Epochs:  20%|██        | 4/20 [02:17<07:20, 27.52s/it, best=13.30, patience=6, val=13.30]

Epochs:  25%|██▌       | 5/20 [02:17<06:56, 27.77s/it, best=13.30, patience=6, val=13.30]

Epochs:  25%|██▌       | 5/20 [02:45<06:56, 27.77s/it, best=11.73, patience=6, val=11.73]

Epochs:  30%|███       | 6/20 [02:45<06:27, 27.70s/it, best=11.73, patience=6, val=11.73]

Epochs:  30%|███       | 6/20 [03:13<06:27, 27.70s/it, best=10.55, patience=6, val=10.55]

Epochs:  35%|███▌      | 7/20 [03:13<06:02, 27.87s/it, best=10.55, patience=6, val=10.55]

Epochs:  35%|███▌      | 7/20 [03:41<06:02, 27.87s/it, best=9.78, patience=6, val=9.78]

Epochs:  40%|████      | 8/20 [03:41<05:36, 28.05s/it, best=9.78, patience=6, val=9.78]

Epochs:  40%|████      | 8/20 [04:10<05:36, 28.05s/it, best=9.39, patience=6, val=9.39]

Epochs:  45%|████▌     | 9/20 [04:10<05:09, 28.15s/it, best=9.39, patience=6, val=9.39]

Epochs:  45%|████▌     | 9/20 [04:38<05:09, 28.15s/it, best=9.20, patience=6, val=9.20]

Epochs:  50%|█████     | 10/20 [04:38<04:42, 28.21s/it, best=9.20, patience=6, val=9.20]

Epochs:  50%|█████     | 10/20 [05:06<04:42, 28.21s/it, best=9.20, patience=5, val=9.26]

Epochs:  55%|█████▌    | 11/20 [05:06<04:13, 28.22s/it, best=9.20, patience=5, val=9.26]

Epochs:  55%|█████▌    | 11/20 [05:35<04:13, 28.22s/it, best=8.81, patience=6, val=8.81]


Fold 3: MAE=6.892, RMSE=8.203, R2=0.8507674932479858, best={'head_lr': 0.001, 'backbone_lr': 1e-05, 'weight_decay': 0.0001}

Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=29.73, patience=6, val=29.73]

Epochs:   5%|▌         | 1/20 [00:28<09:03, 28.58s/it, best=29.73, patience=6, val=29.73]

Epochs:   5%|▌         | 1/20 [00:56<09:03, 28.58s/it, best=17.43, patience=6, val=17.43]

Epochs:  10%|█         | 2/20 [00:56<08:30, 28.35s/it, best=17.43, patience=6, val=17.43]

Epochs:  10%|█         | 2/20 [01:25<08:30, 28.35s/it, best=16.11, patience=6, val=16.11]

Epochs:  15%|█▌        | 3/20 [01:25<08:04, 28.50s/it, best=16.11, patience=6, val=16.11]

Epochs:  15%|█▌        | 3/20 [01:54<08:04, 28.50s/it, best=14.38, patience=6, val=14.38]

Epochs:  20%|██        | 4/20 [01:54<07:38, 28.65s/it, best=14.38, patience=6, val=14.38]

Epochs:  20%|██        | 4/20 [02:23<07:38, 28.65s/it, best=12.79, patience=6, val=12.79]

Epochs:  25%|██▌       | 5/20 [02:23<07:10, 28.69s/it, best=12.79, patience=6, val=12.79]

Epochs:  25%|██▌       | 5/20 [02:52<07:10, 28.69s/it, best=10.94, patience=6, val=10.94]

Epochs:  30%|███       | 6/20 [02:52<06:43, 28.82s/it, best=10.94, patience=6, val=10.94]

Epochs:  30%|███       | 6/20 [03:20<06:43, 28.82s/it, best=9.06, patience=6, val=9.06]

Epochs:  35%|███▌      | 7/20 [03:20<06:14, 28.80s/it, best=9.06, patience=6, val=9.06]

Epochs:  35%|███▌      | 7/20 [03:51<06:14, 28.80s/it, best=8.15, patience=6, val=8.15]

Epochs:  40%|████      | 8/20 [03:51<05:53, 29.43s/it, best=8.15, patience=6, val=8.15]

Epochs:  40%|████      | 8/20 [04:24<05:53, 29.43s/it, best=7.84, patience=6, val=7.84]

Epochs:  45%|████▌     | 9/20 [04:24<05:34, 30.43s/it, best=7.84, patience=6, val=7.84]

Epochs:  45%|████▌     | 9/20 [04:56<05:34, 30.43s/it, best=7.73, patience=6, val=7.73]

Epochs:  50%|█████     | 10/20 [04:56<05:09, 30.94s/it, best=7.73, patience=6, val=7.73]

Epochs:  50%|█████     | 10/20 [05:24<05:09, 30.94s/it, best=7.63, patience=6, val=7.63]

Epochs:  55%|█████▌    | 11/20 [05:24<04:31, 30.18s/it, best=7.63, patience=6, val=7.63]

Epochs:  55%|█████▌    | 11/20 [05:53<04:31, 30.18s/it, best=7.54, patience=6, val=7.54]

Epochs:  60%|██████    | 12/20 [05:53<03:56, 29.60s/it, best=7.54, patience=6, val=7.54]

Epochs:  60%|██████    | 12/20 [06:21<03:56, 29.60s/it, best=7.34, patience=6, val=7.34]

Epochs:  65%|██████▌   | 13/20 [06:21<03:24, 29.21s/it, best=7.34, patience=6, val=7.34]

Epochs:  65%|██████▌   | 13/20 [06:49<03:24, 29.21s/it, best=7.17, patience=6, val=7.17]

Epochs:  70%|███████   | 14/20 [06:49<02:53, 28.96s/it, best=7.17, patience=6, val=7.17]

Epochs:  70%|███████   | 14/20 [07:18<02:53, 28.96s/it, best=7.04, patience=6, val=7.04]

Epochs:  75%|███████▌  | 15/20 [07:18<02:24, 28.89s/it, best=7.04, patience=6, val=7.04]

Epochs:  75%|███████▌  | 15/20 [07:47<02:24, 28.89s/it, best=6.78, patience=6, val=6.78]

Epochs:  80%|████████  | 16/20 [07:47<01:55, 28.84s/it, best=6.78, patience=6, val=6.78]

Epochs:  80%|████████  | 16/20 [08:16<01:55, 28.84s/it, best=6.72, patience=6, val=6.72]

Epochs:  85%|████████▌ | 17/20 [08:16<01:26, 28.87s/it, best=6.72, patience=6, val=6.72]

Epochs:  85%|████████▌ | 17/20 [08:47<01:26, 28.87s/it, best=6.59, patience=6, val=6.59]

Epochs:  90%|█████████ | 18/20 [08:47<00:59, 29.58s/it, best=6.59, patience=6, val=6.59]

Epochs:  90%|█████████ | 18/20 [09:16<00:59, 29.58s/it, best=6.48, patience=6, val=6.48]

Epochs:  95%|█████████▌| 19/20 [09:16<00:29, 29.27s/it, best=6.48, patience=6, val=6.48]

Epochs:  95%|█████████▌| 19/20 [09:44<00:29, 29.27s/it, best=6.43, patience=6, val=6.43]

Epochs: 100%|██████████| 20/20 [09:44<00:00, 29.02s/it, best=6.43, patience=6, val=6.43]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=29.83, patience=6, val=29.83]

Epochs:   5%|▌         | 1/20 [00:28<09:07, 28.80s/it, best=29.83, patience=6, val=29.83]

Epochs:   5%|▌         | 1/20 [01:00<09:07, 28.80s/it, best=18.76, patience=6, val=18.76]

Epochs:  10%|█         | 2/20 [01:00<09:05, 30.33s/it, best=18.76, patience=6, val=18.76]

Epochs:  10%|█         | 2/20 [01:32<09:05, 30.33s/it, best=16.97, patience=6, val=16.97]

Epochs:  15%|█▌        | 3/20 [01:33<08:54, 31.46s/it, best=16.97, patience=6, val=16.97]

Epochs:  15%|█▌        | 3/20 [02:04<08:54, 31.46s/it, best=14.98, patience=6, val=14.98]

Epochs:  20%|██        | 4/20 [02:04<08:26, 31.66s/it, best=14.98, patience=6, val=14.98]

Epochs:  20%|██        | 4/20 [02:37<08:26, 31.66s/it, best=13.58, patience=6, val=13.58]

Epochs:  25%|██▌       | 5/20 [02:37<07:57, 31.86s/it, best=13.58, patience=6, val=13.58]

Epochs:  25%|██▌       | 5/20 [03:06<07:57, 31.86s/it, best=12.20, patience=6, val=12.20]

Epochs:  30%|███       | 6/20 [03:06<07:14, 31.02s/it, best=12.20, patience=6, val=12.20]

Epochs:  30%|███       | 6/20 [03:34<07:14, 31.02s/it, best=10.91, patience=6, val=10.91]

Epochs:  35%|███▌      | 7/20 [03:34<06:30, 30.03s/it, best=10.91, patience=6, val=10.91]

Epochs:  35%|███▌      | 7/20 [04:02<06:30, 30.03s/it, best=9.69, patience=6, val=9.69]

Epochs:  40%|████      | 8/20 [04:02<05:54, 29.51s/it, best=9.69, patience=6, val=9.69]

Epochs:  40%|████      | 8/20 [04:31<05:54, 29.51s/it, best=8.80, patience=6, val=8.80]

Epochs:  45%|████▌     | 9/20 [04:31<05:20, 29.14s/it, best=8.80, patience=6, val=8.80]

Epochs:  45%|████▌     | 9/20 [04:59<05:20, 29.14s/it, best=8.36, patience=6, val=8.36]

Epochs:  50%|█████     | 10/20 [04:59<04:49, 29.00s/it, best=8.36, patience=6, val=8.36]

Epochs:  50%|█████     | 10/20 [05:28<04:49, 29.00s/it, best=8.18, patience=6, val=8.18]

Epochs:  55%|█████▌    | 11/20 [05:28<04:20, 28.96s/it, best=8.18, patience=6, val=8.18]

Epochs:  55%|█████▌    | 11/20 [05:57<04:20, 28.96s/it, best=8.18, patience=5, val=8.21]

Epochs:  60%|██████    | 12/20 [05:57<03:51, 28.98s/it, best=8.18, patience=5, val=8.21]

Epochs:  60%|██████    | 12/20 [06:26<03:51, 28.98s/it, best=8.09, patience=6, val=8.09]

Epochs:  65%|██████▌   | 13/20 [06:26<03:22, 28.93s/it, best=8.09, patience=6, val=8.09]

Epochs:  65%|██████▌   | 13/20 [06:57<03:22, 28.93s/it, best=7.92, patience=6, val=7.92]

Epochs:  70%|███████   | 14/20 [06:57<02:57, 29.51s/it, best=7.92, patience=6, val=7.92]

Epochs:  70%|███████   | 14/20 [07:29<02:57, 29.51s/it, best=7.88, patience=6, val=7.88]

Epochs:  75%|███████▌  | 15/20 [07:29<02:31, 30.36s/it, best=7.88, patience=6, val=7.88]

Epochs:  75%|███████▌  | 15/20 [08:01<02:31, 30.36s/it, best=7.49, patience=6, val=7.49]

Epochs:  80%|████████  | 16/20 [08:01<02:02, 30.66s/it, best=7.49, patience=6, val=7.49]

Epochs:  80%|████████  | 16/20 [08:29<02:02, 30.66s/it, best=7.49, patience=5, val=7.87]

Epochs:  85%|████████▌ | 17/20 [08:29<01:29, 29.91s/it, best=7.49, patience=5, val=7.87]

Epochs:  85%|████████▌ | 17/20 [08:58<01:29, 29.91s/it, best=7.49, patience=4, val=7.77]

Epochs:  90%|█████████ | 18/20 [08:58<00:59, 29.58s/it, best=7.49, patience=4, val=7.77]

Epochs:  90%|█████████ | 18/20 [09:26<00:59, 29.58s/it, best=7.49, patience=3, val=7.86]

Epochs:  95%|█████████▌| 19/20 [09:26<00:29, 29.23s/it, best=7.49, patience=3, val=7.86]

Epochs:  95%|█████████▌| 19/20 [09:55<00:29, 29.23s/it, best=7.49, patience=2, val=7.70]

Epochs: 100%|██████████| 20/20 [09:55<00:00, 29.16s/it, best=7.49, patience=2, val=7.70]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=28.86, patience=6, val=28.86]

Epochs:   5%|▌         | 1/20 [00:28<08:55, 28.20s/it, best=28.86, patience=6, val=28.86]

Epochs:   5%|▌         | 1/20 [00:56<08:55, 28.20s/it, best=17.43, patience=6, val=17.43]

Epochs:  10%|█         | 2/20 [00:56<08:29, 28.32s/it, best=17.43, patience=6, val=17.43]

Epochs:  10%|█         | 2/20 [01:28<08:29, 28.32s/it, best=16.49, patience=6, val=16.49]

Epochs:  15%|█▌        | 3/20 [01:28<08:28, 29.94s/it, best=16.49, patience=6, val=16.49]

Epochs:  15%|█▌        | 3/20 [02:01<08:28, 29.94s/it, best=14.74, patience=6, val=14.74]

Epochs:  20%|██        | 4/20 [02:01<08:17, 31.07s/it, best=14.74, patience=6, val=14.74]

Epochs:  20%|██        | 4/20 [02:30<08:17, 31.07s/it, best=13.25, patience=6, val=13.25]

Epochs:  25%|██▌       | 5/20 [02:30<07:38, 30.58s/it, best=13.25, patience=6, val=13.25]

Epochs:  25%|██▌       | 5/20 [02:59<07:38, 30.58s/it, best=11.86, patience=6, val=11.86]

Epochs:  30%|███       | 6/20 [02:59<06:57, 29.80s/it, best=11.86, patience=6, val=11.86]

Epochs:  30%|███       | 6/20 [03:31<06:57, 29.80s/it, best=10.57, patience=6, val=10.57]

Epochs:  35%|███▌      | 7/20 [03:31<06:38, 30.62s/it, best=10.57, patience=6, val=10.57]

Epochs:  35%|███▌      | 7/20 [04:04<06:38, 30.62s/it, best=9.28, patience=6, val=9.28]

Epochs:  40%|████      | 8/20 [04:04<06:15, 31.26s/it, best=9.28, patience=6, val=9.28]

Epochs:  40%|████      | 8/20 [04:33<06:15, 31.26s/it, best=8.15, patience=6, val=8.15]

Epochs:  45%|████▌     | 9/20 [04:33<05:36, 30.63s/it, best=8.15, patience=6, val=8.15]

Epochs:  45%|████▌     | 9/20 [05:01<05:36, 30.63s/it, best=7.56, patience=6, val=7.56]

Epochs:  50%|█████     | 10/20 [05:01<04:58, 29.84s/it, best=7.56, patience=6, val=7.56]

Epochs:  50%|█████     | 10/20 [05:30<04:58, 29.84s/it, best=7.16, patience=6, val=7.16]

Epochs:  55%|█████▌    | 11/20 [05:30<04:25, 29.46s/it, best=7.16, patience=6, val=7.16]

Epochs:  55%|█████▌    | 11/20 [05:58<04:25, 29.46s/it, best=7.06, patience=6, val=7.06]

Epochs:  60%|██████    | 12/20 [05:58<03:53, 29.23s/it, best=7.06, patience=6, val=7.06]

Epochs:  60%|██████    | 12/20 [06:27<03:53, 29.23s/it, best=6.50, patience=6, val=6.50]

Epochs:  65%|██████▌   | 13/20 [06:27<03:23, 29.08s/it, best=6.50, patience=6, val=6.50]

Epochs:  65%|██████▌   | 13/20 [06:55<03:23, 29.08s/it, best=6.17, patience=6, val=6.17]

Epochs:  70%|███████   | 14/20 [06:55<02:53, 28.87s/it, best=6.17, patience=6, val=6.17]

Epochs:  70%|███████   | 14/20 [07:24<02:53, 28.87s/it, best=5.81, patience=6, val=5.81]

Epochs:  75%|███████▌  | 15/20 [07:24<02:23, 28.76s/it, best=5.81, patience=6, val=5.81]

Epochs:  75%|███████▌  | 15/20 [07:53<02:23, 28.76s/it, best=5.81, patience=5, val=6.03]

Epochs:  80%|████████  | 16/20 [07:53<01:54, 28.74s/it, best=5.81, patience=5, val=6.03]

Epochs:  80%|████████  | 16/20 [08:25<01:54, 28.74s/it, best=5.81, patience=4, val=5.93]

Epochs:  85%|████████▌ | 17/20 [08:25<01:29, 29.88s/it, best=5.81, patience=4, val=5.93]

Epochs:  85%|████████▌ | 17/20 [08:58<01:29, 29.88s/it, best=5.81, patience=3, val=6.18]

Epochs:  90%|█████████ | 18/20 [08:58<01:01, 30.65s/it, best=5.81, patience=3, val=6.18]

Epochs:  90%|█████████ | 18/20 [09:28<01:01, 30.65s/it, best=5.73, patience=6, val=5.73]

Epochs:  95%|█████████▌| 19/20 [09:28<00:30, 30.70s/it, best=5.73, patience=6, val=5.73]

Epochs:  95%|█████████▌| 19/20 [09:57<00:30, 30.70s/it, best=5.41, patience=6, val=5.41]

Epochs: 100%|██████████| 20/20 [09:57<00:00, 29.92s/it, best=5.41, patience=6, val=5.41]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=30.92, patience=6, val=30.92]

Epochs:   5%|▌         | 1/20 [00:28<08:58, 28.33s/it, best=30.92, patience=6, val=30.92]

Epochs:   5%|▌         | 1/20 [00:56<08:58, 28.33s/it, best=17.46, patience=6, val=17.46]

Epochs:  10%|█         | 2/20 [00:56<08:30, 28.33s/it, best=17.46, patience=6, val=17.46]

Epochs:  10%|█         | 2/20 [01:25<08:30, 28.33s/it, best=14.77, patience=6, val=14.77]

Epochs:  15%|█▌        | 3/20 [01:25<08:08, 28.72s/it, best=14.77, patience=6, val=14.77]

Epochs:  15%|█▌        | 3/20 [01:55<08:08, 28.72s/it, best=13.11, patience=6, val=13.11]

Epochs:  20%|██        | 4/20 [01:55<07:42, 28.92s/it, best=13.11, patience=6, val=13.11]

Epochs:  20%|██        | 4/20 [02:23<07:42, 28.92s/it, best=12.46, patience=6, val=12.46]

Epochs:  25%|██▌       | 5/20 [02:23<07:13, 28.88s/it, best=12.46, patience=6, val=12.46]

Epochs:  25%|██▌       | 5/20 [02:54<07:13, 28.88s/it, best=11.10, patience=6, val=11.10]

Epochs:  30%|███       | 6/20 [02:54<06:54, 29.58s/it, best=11.10, patience=6, val=11.10]

Epochs:  30%|███       | 6/20 [03:27<06:54, 29.58s/it, best=10.21, patience=6, val=10.21]

Epochs:  35%|███▌      | 7/20 [03:27<06:37, 30.56s/it, best=10.21, patience=6, val=10.21]

Epochs:  35%|███▌      | 7/20 [03:59<06:37, 30.56s/it, best=9.88, patience=6, val=9.88]

Epochs:  40%|████      | 8/20 [03:59<06:13, 31.16s/it, best=9.88, patience=6, val=9.88]

Epochs:  40%|████      | 8/20 [04:31<06:13, 31.16s/it, best=9.69, patience=6, val=9.69]

Epochs:  45%|████▌     | 9/20 [04:31<05:45, 31.40s/it, best=9.69, patience=6, val=9.69]

Epochs:  45%|████▌     | 9/20 [05:02<05:45, 31.40s/it, best=9.28, patience=6, val=9.28]

Epochs:  50%|█████     | 10/20 [05:02<05:10, 31.10s/it, best=9.28, patience=6, val=9.28]

Epochs:  50%|█████     | 10/20 [05:30<05:10, 31.10s/it, best=9.04, patience=6, val=9.04]

Epochs:  55%|█████▌    | 11/20 [05:30<04:30, 30.10s/it, best=9.04, patience=6, val=9.04]

Epochs:  55%|█████▌    | 11/20 [05:58<04:30, 30.10s/it, best=8.75, patience=6, val=8.75]

Epochs:  60%|██████    | 12/20 [05:58<03:56, 29.50s/it, best=8.75, patience=6, val=8.75]

Epochs:  60%|██████    | 12/20 [06:26<03:56, 29.50s/it, best=7.97, patience=6, val=7.97]

Epochs:  65%|██████▌   | 13/20 [06:26<03:24, 29.21s/it, best=7.97, patience=6, val=7.97]

Epochs:  65%|██████▌   | 13/20 [06:55<03:24, 29.21s/it, best=7.65, patience=6, val=7.65]

Epochs:  70%|███████   | 14/20 [06:55<02:53, 28.98s/it, best=7.65, patience=6, val=7.65]

Epochs:  70%|███████   | 14/20 [07:23<02:53, 28.98s/it, best=7.19, patience=6, val=7.19]

Epochs:  75%|███████▌  | 15/20 [07:23<02:24, 28.87s/it, best=7.19, patience=6, val=7.19]

Epochs:  75%|███████▌  | 15/20 [07:52<02:24, 28.87s/it, best=7.19, patience=5, val=7.26]

Epochs:  80%|████████  | 16/20 [07:52<01:54, 28.70s/it, best=7.19, patience=5, val=7.26]

Epochs:  80%|████████  | 16/20 [08:20<01:54, 28.70s/it, best=6.57, patience=6, val=6.57]

Epochs:  85%|████████▌ | 17/20 [08:20<01:26, 28.68s/it, best=6.57, patience=6, val=6.57]

Epochs:  85%|████████▌ | 17/20 [08:49<01:26, 28.68s/it, best=6.57, patience=5, val=6.62]

Epochs:  90%|█████████ | 18/20 [08:49<00:57, 28.75s/it, best=6.57, patience=5, val=6.62]

Epochs:  90%|█████████ | 18/20 [09:19<00:57, 28.75s/it, best=6.57, patience=4, val=6.65]

Epochs:  95%|█████████▌| 19/20 [09:19<00:29, 29.04s/it, best=6.57, patience=4, val=6.65]

Epochs:  95%|█████████▌| 19/20 [09:52<00:29, 29.04s/it, best=6.54, patience=6, val=6.54]

Epochs: 100%|██████████| 20/20 [09:52<00:00, 30.23s/it, best=6.54, patience=6, val=6.54]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:32<?, ?it/s, best=29.96, patience=6, val=29.96]

Epochs:   5%|▌         | 1/20 [00:32<10:11, 32.20s/it, best=29.96, patience=6, val=29.96]

Epochs:   5%|▌         | 1/20 [01:05<10:11, 32.20s/it, best=17.64, patience=6, val=17.64]

Epochs:  10%|█         | 2/20 [01:05<09:48, 32.68s/it, best=17.64, patience=6, val=17.64]

Epochs:  10%|█         | 2/20 [01:34<09:48, 32.68s/it, best=16.66, patience=6, val=16.66]

Epochs:  15%|█▌        | 3/20 [01:34<08:50, 31.23s/it, best=16.66, patience=6, val=16.66]

Epochs:  15%|█▌        | 3/20 [02:03<08:50, 31.23s/it, best=14.66, patience=6, val=14.66]

Epochs:  20%|██        | 4/20 [02:03<08:04, 30.25s/it, best=14.66, patience=6, val=14.66]

Epochs:  20%|██        | 4/20 [02:32<08:04, 30.25s/it, best=13.80, patience=6, val=13.80]

Epochs:  25%|██▌       | 5/20 [02:32<07:27, 29.84s/it, best=13.80, patience=6, val=13.80]

Epochs:  25%|██▌       | 5/20 [03:01<07:27, 29.84s/it, best=12.29, patience=6, val=12.29]

Epochs:  30%|███       | 6/20 [03:01<06:53, 29.51s/it, best=12.29, patience=6, val=12.29]

Epochs:  30%|███       | 6/20 [03:32<06:53, 29.51s/it, best=12.17, patience=6, val=12.17]

Epochs:  35%|███▌      | 7/20 [03:32<06:30, 30.01s/it, best=12.17, patience=6, val=12.17]

Epochs:  35%|███▌      | 7/20 [04:05<06:30, 30.01s/it, best=11.86, patience=6, val=11.86]

Epochs:  40%|████      | 8/20 [04:05<06:11, 30.98s/it, best=11.86, patience=6, val=11.86]

Epochs:  40%|████      | 8/20 [04:38<06:11, 30.98s/it, best=11.28, patience=6, val=11.28]

Epochs:  45%|████▌     | 9/20 [04:38<05:46, 31.52s/it, best=11.28, patience=6, val=11.28]

Epochs:  45%|████▌     | 9/20 [05:07<05:46, 31.52s/it, best=11.05, patience=6, val=11.05]

Epochs:  50%|█████     | 10/20 [05:07<05:07, 30.74s/it, best=11.05, patience=6, val=11.05]

Epochs:  50%|█████     | 10/20 [05:36<05:07, 30.74s/it, best=11.03, patience=6, val=11.03]

Epochs:  55%|█████▌    | 11/20 [05:36<04:31, 30.15s/it, best=11.03, patience=6, val=11.03]

Epochs:  55%|█████▌    | 11/20 [06:04<04:31, 30.15s/it, best=10.73, patience=6, val=10.73]

Epochs:  60%|██████    | 12/20 [06:04<03:57, 29.74s/it, best=10.73, patience=6, val=10.73]

Epochs:  60%|██████    | 12/20 [06:34<03:57, 29.74s/it, best=10.68, patience=6, val=10.68]

Epochs:  65%|██████▌   | 13/20 [06:34<03:26, 29.56s/it, best=10.68, patience=6, val=10.68]

Epochs:  65%|██████▌   | 13/20 [07:03<03:26, 29.56s/it, best=10.46, patience=6, val=10.46]

Epochs:  70%|███████   | 14/20 [07:03<02:56, 29.42s/it, best=10.46, patience=6, val=10.46]

Epochs:  70%|███████   | 14/20 [07:31<02:56, 29.42s/it, best=10.46, patience=5, val=10.55]

Epochs:  75%|███████▌  | 15/20 [07:31<02:26, 29.21s/it, best=10.46, patience=5, val=10.55]

Epochs:  75%|███████▌  | 15/20 [08:00<02:26, 29.21s/it, best=10.46, patience=4, val=10.47]

Epochs:  80%|████████  | 16/20 [08:00<01:56, 29.08s/it, best=10.46, patience=4, val=10.47]

Epochs:  80%|████████  | 16/20 [08:31<01:56, 29.08s/it, best=10.12, patience=6, val=10.12]

Epochs:  85%|████████▌ | 17/20 [08:31<01:28, 29.56s/it, best=10.12, patience=6, val=10.12]

Epochs:  85%|████████▌ | 17/20 [09:04<01:28, 29.56s/it, best=10.12, patience=5, val=10.85]

Epochs:  90%|█████████ | 18/20 [09:04<01:01, 30.55s/it, best=10.12, patience=5, val=10.85]

Epochs:  90%|█████████ | 18/20 [09:37<01:01, 30.55s/it, best=10.12, patience=4, val=10.45]

Epochs:  95%|█████████▌| 19/20 [09:37<00:31, 31.32s/it, best=10.12, patience=4, val=10.45]

Epochs:  95%|█████████▌| 19/20 [10:09<00:31, 31.32s/it, best=10.12, patience=3, val=10.38]

Epochs: 100%|██████████| 20/20 [10:09<00:00, 31.66s/it, best=10.12, patience=3, val=10.38]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:32<?, ?it/s, best=28.97, patience=6, val=28.97]

Epochs:   5%|▌         | 1/20 [00:32<10:21, 32.69s/it, best=28.97, patience=6, val=28.97]

Epochs:   5%|▌         | 1/20 [01:02<10:21, 32.69s/it, best=17.08, patience=6, val=17.08]

Epochs:  10%|█         | 2/20 [01:02<09:21, 31.17s/it, best=17.08, patience=6, val=17.08]

Epochs:  10%|█         | 2/20 [01:31<09:21, 31.17s/it, best=16.04, patience=6, val=16.04]

Epochs:  15%|█▌        | 3/20 [01:31<08:27, 29.83s/it, best=16.04, patience=6, val=16.04]

Epochs:  15%|█▌        | 3/20 [01:58<08:27, 29.83s/it, best=13.86, patience=6, val=13.86]

Epochs:  20%|██        | 4/20 [01:58<07:45, 29.09s/it, best=13.86, patience=6, val=13.86]

Epochs:  20%|██        | 4/20 [02:27<07:45, 29.09s/it, best=12.29, patience=6, val=12.29]

Epochs:  25%|██▌       | 5/20 [02:27<07:12, 28.84s/it, best=12.29, patience=6, val=12.29]

Epochs:  25%|██▌       | 5/20 [02:55<07:12, 28.84s/it, best=10.85, patience=6, val=10.85]

Epochs:  30%|███       | 6/20 [02:55<06:41, 28.70s/it, best=10.85, patience=6, val=10.85]

Epochs:  30%|███       | 6/20 [03:24<06:41, 28.70s/it, best=9.76, patience=6, val=9.76]

Epochs:  35%|███▌      | 7/20 [03:24<06:11, 28.58s/it, best=9.76, patience=6, val=9.76]

Epochs:  35%|███▌      | 7/20 [03:52<06:11, 28.58s/it, best=8.96, patience=6, val=8.96]

Epochs:  40%|████      | 8/20 [03:52<05:43, 28.61s/it, best=8.96, patience=6, val=8.96]

Epochs:  40%|████      | 8/20 [04:21<05:43, 28.61s/it, best=8.09, patience=6, val=8.09]

Epochs:  45%|████▌     | 9/20 [04:21<05:15, 28.71s/it, best=8.09, patience=6, val=8.09]


Fold 4: MAE=7.028, RMSE=8.744, R2=0.8249538540840149, best={'head_lr': 0.001, 'backbone_lr': 1e-05, 'weight_decay': 0.0001}

Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:27<?, ?it/s, best=32.20, patience=6, val=32.20]

Epochs:   5%|▌         | 1/20 [00:27<08:49, 27.87s/it, best=32.20, patience=6, val=32.20]

Epochs:   5%|▌         | 1/20 [00:56<08:49, 27.87s/it, best=18.28, patience=6, val=18.28]

Epochs:  10%|█         | 2/20 [00:56<08:25, 28.10s/it, best=18.28, patience=6, val=18.28]

Epochs:  10%|█         | 2/20 [01:24<08:25, 28.10s/it, best=16.43, patience=6, val=16.43]

Epochs:  15%|█▌        | 3/20 [01:24<07:58, 28.17s/it, best=16.43, patience=6, val=16.43]

Epochs:  15%|█▌        | 3/20 [01:53<07:58, 28.17s/it, best=14.58, patience=6, val=14.58]

Epochs:  20%|██        | 4/20 [01:53<07:35, 28.47s/it, best=14.58, patience=6, val=14.58]

Epochs:  20%|██        | 4/20 [02:21<07:35, 28.47s/it, best=12.69, patience=6, val=12.69]

Epochs:  25%|██▌       | 5/20 [02:21<07:08, 28.55s/it, best=12.69, patience=6, val=12.69]

Epochs:  25%|██▌       | 5/20 [02:50<07:08, 28.55s/it, best=10.84, patience=6, val=10.84]

Epochs:  30%|███       | 6/20 [02:50<06:40, 28.57s/it, best=10.84, patience=6, val=10.84]

Epochs:  30%|███       | 6/20 [03:19<06:40, 28.57s/it, best=9.51, patience=6, val=9.51]

Epochs:  35%|███▌      | 7/20 [03:19<06:11, 28.59s/it, best=9.51, patience=6, val=9.51]

Epochs:  35%|███▌      | 7/20 [03:47<06:11, 28.59s/it, best=8.17, patience=6, val=8.17]

Epochs:  40%|████      | 8/20 [03:47<05:42, 28.57s/it, best=8.17, patience=6, val=8.17]

Epochs:  40%|████      | 8/20 [04:16<05:42, 28.57s/it, best=7.60, patience=6, val=7.60]

Epochs:  45%|████▌     | 9/20 [04:16<05:13, 28.52s/it, best=7.60, patience=6, val=7.60]

Epochs:  45%|████▌     | 9/20 [04:47<05:13, 28.52s/it, best=7.16, patience=6, val=7.16]

Epochs:  50%|█████     | 10/20 [04:47<04:52, 29.24s/it, best=7.16, patience=6, val=7.16]

Epochs:  50%|█████     | 10/20 [05:19<04:52, 29.24s/it, best=6.82, patience=6, val=6.82]

Epochs:  55%|█████▌    | 11/20 [05:19<04:31, 30.21s/it, best=6.82, patience=6, val=6.82]

Epochs:  55%|█████▌    | 11/20 [05:52<04:31, 30.21s/it, best=6.82, patience=5, val=6.88]

Epochs:  60%|██████    | 12/20 [05:52<04:07, 30.93s/it, best=6.82, patience=5, val=6.88]

Epochs:  60%|██████    | 12/20 [06:24<04:07, 30.93s/it, best=6.47, patience=6, val=6.47]

Epochs:  65%|██████▌   | 13/20 [06:24<03:39, 31.34s/it, best=6.47, patience=6, val=6.47]

Epochs:  65%|██████▌   | 13/20 [06:56<03:39, 31.34s/it, best=6.47, patience=5, val=7.50]

Epochs:  70%|███████   | 14/20 [06:56<03:09, 31.56s/it, best=6.47, patience=5, val=7.50]

Epochs:  70%|███████   | 14/20 [07:25<03:09, 31.56s/it, best=6.47, patience=4, val=6.49]

Epochs:  75%|███████▌  | 15/20 [07:25<02:33, 30.78s/it, best=6.47, patience=4, val=6.49]

Epochs:  75%|███████▌  | 15/20 [07:53<02:33, 30.78s/it, best=6.29, patience=6, val=6.29]

Epochs:  80%|████████  | 16/20 [07:53<01:59, 29.85s/it, best=6.29, patience=6, val=6.29]

Epochs:  80%|████████  | 16/20 [08:21<01:59, 29.85s/it, best=6.28, patience=6, val=6.28]

Epochs:  85%|████████▌ | 17/20 [08:21<01:28, 29.39s/it, best=6.28, patience=6, val=6.28]

Epochs:  85%|████████▌ | 17/20 [08:49<01:28, 29.39s/it, best=6.28, patience=5, val=6.32]

Epochs:  90%|█████████ | 18/20 [08:49<00:58, 29.07s/it, best=6.28, patience=5, val=6.32]

Epochs:  90%|█████████ | 18/20 [09:18<00:58, 29.07s/it, best=6.28, patience=4, val=6.40]

Epochs:  95%|█████████▌| 19/20 [09:18<00:28, 28.99s/it, best=6.28, patience=4, val=6.40]

Epochs:  95%|█████████▌| 19/20 [09:46<00:28, 28.99s/it, best=6.28, patience=3, val=6.34]

Epochs: 100%|██████████| 20/20 [09:46<00:00, 28.84s/it, best=6.28, patience=3, val=6.34]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:28<?, ?it/s, best=31.72, patience=6, val=31.72]

Epochs:   5%|▌         | 1/20 [00:28<09:04, 28.67s/it, best=31.72, patience=6, val=31.72]

Epochs:   5%|▌         | 1/20 [00:56<09:04, 28.67s/it, best=18.40, patience=6, val=18.40]

Epochs:  10%|█         | 2/20 [00:56<08:31, 28.41s/it, best=18.40, patience=6, val=18.40]

Epochs:  10%|█         | 2/20 [01:26<08:31, 28.41s/it, best=17.49, patience=6, val=17.49]

Epochs:  15%|█▌        | 3/20 [01:26<08:10, 28.83s/it, best=17.49, patience=6, val=17.49]

Epochs:  15%|█▌        | 3/20 [01:55<08:10, 28.83s/it, best=15.34, patience=6, val=15.34]

Epochs:  20%|██        | 4/20 [01:55<07:41, 28.86s/it, best=15.34, patience=6, val=15.34]

Epochs:  20%|██        | 4/20 [02:24<07:41, 28.86s/it, best=13.21, patience=6, val=13.21]

Epochs:  25%|██▌       | 5/20 [02:24<07:13, 28.89s/it, best=13.21, patience=6, val=13.21]

Epochs:  25%|██▌       | 5/20 [02:56<07:13, 28.89s/it, best=11.88, patience=6, val=11.88]

Epochs:  30%|███       | 6/20 [02:56<07:00, 30.02s/it, best=11.88, patience=6, val=11.88]

Epochs:  30%|███       | 6/20 [03:28<07:00, 30.02s/it, best=10.73, patience=6, val=10.73]

Epochs:  35%|███▌      | 7/20 [03:28<06:37, 30.60s/it, best=10.73, patience=6, val=10.73]

Epochs:  35%|███▌      | 7/20 [04:00<06:37, 30.60s/it, best=8.82, patience=6, val=8.82]

Epochs:  40%|████      | 8/20 [04:00<06:14, 31.18s/it, best=8.82, patience=6, val=8.82]

Epochs:  40%|████      | 8/20 [04:32<06:14, 31.18s/it, best=8.29, patience=6, val=8.29]

Epochs:  45%|████▌     | 9/20 [04:32<05:45, 31.42s/it, best=8.29, patience=6, val=8.29]

Epochs:  45%|████▌     | 9/20 [05:02<05:45, 31.42s/it, best=8.00, patience=6, val=8.00]

Epochs:  50%|█████     | 10/20 [05:02<05:11, 31.12s/it, best=8.00, patience=6, val=8.00]

Epochs:  50%|█████     | 10/20 [05:30<05:11, 31.12s/it, best=7.86, patience=6, val=7.86]

Epochs:  55%|█████▌    | 11/20 [05:30<04:31, 30.15s/it, best=7.86, patience=6, val=7.86]

Epochs:  55%|█████▌    | 11/20 [05:58<04:31, 30.15s/it, best=7.67, patience=6, val=7.67]

Epochs:  60%|██████    | 12/20 [05:58<03:55, 29.48s/it, best=7.67, patience=6, val=7.67]

Epochs:  60%|██████    | 12/20 [06:26<03:55, 29.48s/it, best=7.37, patience=6, val=7.37]

Epochs:  65%|██████▌   | 13/20 [06:26<03:22, 28.95s/it, best=7.37, patience=6, val=7.37]

Epochs:  65%|██████▌   | 13/20 [06:54<03:22, 28.95s/it, best=7.22, patience=6, val=7.22]

Epochs:  70%|███████   | 14/20 [06:54<02:52, 28.74s/it, best=7.22, patience=6, val=7.22]

Epochs:  70%|███████   | 14/20 [07:23<02:52, 28.74s/it, best=7.07, patience=6, val=7.07]

Epochs:  75%|███████▌  | 15/20 [07:23<02:23, 28.71s/it, best=7.07, patience=6, val=7.07]

Epochs:  75%|███████▌  | 15/20 [07:52<02:23, 28.71s/it, best=7.07, patience=5, val=7.14]

Epochs:  80%|████████  | 16/20 [07:52<01:55, 28.96s/it, best=7.07, patience=5, val=7.14]

Epochs:  80%|████████  | 16/20 [08:25<01:55, 28.96s/it, best=7.05, patience=6, val=7.05]

Epochs:  85%|████████▌ | 17/20 [08:25<01:29, 29.92s/it, best=7.05, patience=6, val=7.05]

Epochs:  85%|████████▌ | 17/20 [08:57<01:29, 29.92s/it, best=6.90, patience=6, val=6.90]

Epochs:  90%|█████████ | 18/20 [08:57<01:01, 30.78s/it, best=6.90, patience=6, val=6.90]

Epochs:  90%|█████████ | 18/20 [09:29<01:01, 30.78s/it, best=6.90, patience=5, val=7.41]

Epochs:  95%|█████████▌| 19/20 [09:29<00:31, 31.15s/it, best=6.90, patience=5, val=7.41]

Epochs:  95%|█████████▌| 19/20 [09:57<00:31, 31.15s/it, best=6.90, patience=4, val=6.94]

Epochs: 100%|██████████| 20/20 [09:57<00:00, 30.16s/it, best=6.90, patience=4, val=6.94]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:27<?, ?it/s, best=31.57, patience=6, val=31.57]

Epochs:   5%|▌         | 1/20 [00:27<08:45, 27.66s/it, best=31.57, patience=6, val=31.57]

Epochs:   5%|▌         | 1/20 [00:55<08:45, 27.66s/it, best=17.78, patience=6, val=17.78]

Epochs:  10%|█         | 2/20 [00:55<08:20, 27.83s/it, best=17.78, patience=6, val=17.78]

Epochs:  10%|█         | 2/20 [01:24<08:20, 27.83s/it, best=16.35, patience=6, val=16.35]

Epochs:  15%|█▌        | 3/20 [01:24<08:04, 28.48s/it, best=16.35, patience=6, val=16.35]

Epochs:  15%|█▌        | 3/20 [01:53<08:04, 28.48s/it, best=14.66, patience=6, val=14.66]

Epochs:  20%|██        | 4/20 [01:53<07:38, 28.68s/it, best=14.66, patience=6, val=14.66]

Epochs:  20%|██        | 4/20 [02:22<07:38, 28.68s/it, best=13.76, patience=6, val=13.76]

Epochs:  25%|██▌       | 5/20 [02:22<07:10, 28.73s/it, best=13.76, patience=6, val=13.76]

Epochs:  25%|██▌       | 5/20 [02:53<07:10, 28.73s/it, best=12.44, patience=6, val=12.44]

Epochs:  30%|███       | 6/20 [02:53<06:52, 29.46s/it, best=12.44, patience=6, val=12.44]

Epochs:  30%|███       | 6/20 [03:26<06:52, 29.46s/it, best=11.76, patience=6, val=11.76]

Epochs:  35%|███▌      | 7/20 [03:26<06:36, 30.53s/it, best=11.76, patience=6, val=11.76]

Epochs:  35%|███▌      | 7/20 [03:58<06:36, 30.53s/it, best=11.76, patience=5, val=11.97]

Epochs:  40%|████      | 8/20 [03:58<06:14, 31.21s/it, best=11.76, patience=5, val=11.97]

Epochs:  40%|████      | 8/20 [04:31<06:14, 31.21s/it, best=11.59, patience=6, val=11.59]

Epochs:  45%|████▌     | 9/20 [04:31<05:48, 31.66s/it, best=11.59, patience=6, val=11.59]

Epochs:  45%|████▌     | 9/20 [05:04<05:48, 31.66s/it, best=11.00, patience=6, val=11.00]

Epochs:  50%|█████     | 10/20 [05:04<05:18, 31.89s/it, best=11.00, patience=6, val=11.00]

Epochs:  50%|█████     | 10/20 [05:36<05:18, 31.89s/it, best=10.77, patience=6, val=10.77]

Epochs:  55%|█████▌    | 11/20 [05:36<04:47, 31.97s/it, best=10.77, patience=6, val=10.77]

Epochs:  55%|█████▌    | 11/20 [06:04<04:47, 31.97s/it, best=10.40, patience=6, val=10.40]

Epochs:  60%|██████    | 12/20 [06:04<04:07, 30.94s/it, best=10.40, patience=6, val=10.40]

Epochs:  60%|██████    | 12/20 [06:32<04:07, 30.94s/it, best=10.19, patience=6, val=10.19]

Epochs:  65%|██████▌   | 13/20 [06:32<03:30, 30.06s/it, best=10.19, patience=6, val=10.19]

Epochs:  65%|██████▌   | 13/20 [07:01<03:30, 30.06s/it, best=10.19, patience=5, val=10.60]

Epochs:  70%|███████   | 14/20 [07:01<02:57, 29.62s/it, best=10.19, patience=5, val=10.60]

Epochs:  70%|███████   | 14/20 [07:29<02:57, 29.62s/it, best=10.18, patience=6, val=10.18]

Epochs:  75%|███████▌  | 15/20 [07:29<02:26, 29.30s/it, best=10.18, patience=6, val=10.18]

Epochs:  75%|███████▌  | 15/20 [07:58<02:26, 29.30s/it, best=10.01, patience=6, val=10.01]

Epochs:  80%|████████  | 16/20 [07:58<01:56, 29.07s/it, best=10.01, patience=6, val=10.01]

Epochs:  80%|████████  | 16/20 [08:27<01:56, 29.07s/it, best=9.87, patience=6, val=9.87]

Epochs:  85%|████████▌ | 17/20 [08:27<01:27, 29.06s/it, best=9.87, patience=6, val=9.87]

Epochs:  85%|████████▌ | 17/20 [08:56<01:27, 29.06s/it, best=9.49, patience=6, val=9.49]

Epochs:  90%|█████████ | 18/20 [08:56<00:58, 29.03s/it, best=9.49, patience=6, val=9.49]

Epochs:  90%|█████████ | 18/20 [09:24<00:58, 29.03s/it, best=9.49, patience=5, val=9.69]

Epochs:  95%|█████████▌| 19/20 [09:24<00:28, 28.84s/it, best=9.49, patience=5, val=9.69]

Epochs:  95%|█████████▌| 19/20 [09:53<00:28, 28.84s/it, best=9.08, patience=6, val=9.08]

Epochs: 100%|██████████| 20/20 [09:53<00:00, 28.71s/it, best=9.08, patience=6, val=9.08]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:32<?, ?it/s, best=33.32, patience=6, val=33.32]

Epochs:   5%|▌         | 1/20 [00:32<10:09, 32.10s/it, best=33.32, patience=6, val=33.32]

Epochs:   5%|▌         | 1/20 [01:04<10:09, 32.10s/it, best=18.77, patience=6, val=18.77]

Epochs:  10%|█         | 2/20 [01:04<09:36, 32.02s/it, best=18.77, patience=6, val=18.77]

Epochs:  10%|█         | 2/20 [01:36<09:36, 32.02s/it, best=15.73, patience=6, val=15.73]

Epochs:  15%|█▌        | 3/20 [01:36<09:10, 32.36s/it, best=15.73, patience=6, val=15.73]

Epochs:  15%|█▌        | 3/20 [02:09<09:10, 32.36s/it, best=14.32, patience=6, val=14.32]

Epochs:  20%|██        | 4/20 [02:09<08:38, 32.43s/it, best=14.32, patience=6, val=14.32]

Epochs:  20%|██        | 4/20 [02:41<08:38, 32.43s/it, best=13.63, patience=6, val=13.63]

Epochs:  25%|██▌       | 5/20 [02:41<08:05, 32.36s/it, best=13.63, patience=6, val=13.63]

Epochs:  25%|██▌       | 5/20 [03:10<08:05, 32.36s/it, best=12.17, patience=6, val=12.17]

Epochs:  30%|███       | 6/20 [03:10<07:16, 31.15s/it, best=12.17, patience=6, val=12.17]

Epochs:  30%|███       | 6/20 [03:38<07:16, 31.15s/it, best=11.21, patience=6, val=11.21]

Epochs:  35%|███▌      | 7/20 [03:38<06:32, 30.17s/it, best=11.21, patience=6, val=11.21]

Epochs:  35%|███▌      | 7/20 [04:07<06:32, 30.17s/it, best=10.57, patience=6, val=10.57]

Epochs:  40%|████      | 8/20 [04:07<05:55, 29.63s/it, best=10.57, patience=6, val=10.57]

Epochs:  40%|████      | 8/20 [04:35<05:55, 29.63s/it, best=9.90, patience=6, val=9.90]

Epochs:  45%|████▌     | 9/20 [04:35<05:22, 29.29s/it, best=9.90, patience=6, val=9.90]

Epochs:  45%|████▌     | 9/20 [05:04<05:22, 29.29s/it, best=9.40, patience=6, val=9.40]

Epochs:  50%|█████     | 10/20 [05:04<04:51, 29.18s/it, best=9.40, patience=6, val=9.40]

Epochs:  50%|█████     | 10/20 [05:33<04:51, 29.18s/it, best=9.05, patience=6, val=9.05]

Epochs:  55%|█████▌    | 11/20 [05:33<04:21, 29.08s/it, best=9.05, patience=6, val=9.05]

Epochs:  55%|█████▌    | 11/20 [06:02<04:21, 29.08s/it, best=8.57, patience=6, val=8.57]

Epochs:  60%|██████    | 12/20 [06:02<03:52, 29.03s/it, best=8.57, patience=6, val=8.57]

Epochs:  60%|██████    | 12/20 [06:31<03:52, 29.03s/it, best=8.35, patience=6, val=8.35]

Epochs:  65%|██████▌   | 13/20 [06:31<03:23, 29.14s/it, best=8.35, patience=6, val=8.35]

Epochs:  65%|██████▌   | 13/20 [07:00<03:23, 29.14s/it, best=8.33, patience=6, val=8.33]

Epochs:  70%|███████   | 14/20 [07:00<02:54, 29.12s/it, best=8.33, patience=6, val=8.33]

Epochs:  70%|███████   | 14/20 [07:30<02:54, 29.12s/it, best=7.89, patience=6, val=7.89]

Epochs:  75%|███████▌  | 15/20 [07:30<02:25, 29.16s/it, best=7.89, patience=6, val=7.89]

Epochs:  75%|███████▌  | 15/20 [08:02<02:25, 29.16s/it, best=7.81, patience=6, val=7.81]

Epochs:  80%|████████  | 16/20 [08:02<02:00, 30.17s/it, best=7.81, patience=6, val=7.81]

Epochs:  80%|████████  | 16/20 [08:35<02:00, 30.17s/it, best=7.81, patience=5, val=7.98]

Epochs:  85%|████████▌ | 17/20 [08:35<01:32, 30.94s/it, best=7.81, patience=5, val=7.98]

Epochs:  85%|████████▌ | 17/20 [09:07<01:32, 30.94s/it, best=7.69, patience=6, val=7.69]

Epochs:  90%|█████████ | 18/20 [09:07<01:02, 31.44s/it, best=7.69, patience=6, val=7.69]

Epochs:  90%|█████████ | 18/20 [09:41<01:02, 31.44s/it, best=7.69, patience=5, val=8.08]

Epochs:  95%|█████████▌| 19/20 [09:41<00:31, 31.98s/it, best=7.69, patience=5, val=8.08]

Epochs:  95%|█████████▌| 19/20 [10:13<00:31, 31.98s/it, best=7.55, patience=6, val=7.55]

Epochs: 100%|██████████| 20/20 [10:13<00:00, 32.05s/it, best=7.55, patience=6, val=7.55]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:27<?, ?it/s, best=32.55, patience=6, val=32.55]

Epochs:   5%|▌         | 1/20 [00:27<08:46, 27.73s/it, best=32.55, patience=6, val=32.55]

Epochs:   5%|▌         | 1/20 [00:56<08:46, 27.73s/it, best=18.48, patience=6, val=18.48]

Epochs:  10%|█         | 2/20 [00:56<08:26, 28.12s/it, best=18.48, patience=6, val=18.48]

Epochs:  10%|█         | 2/20 [01:24<08:26, 28.12s/it, best=16.35, patience=6, val=16.35]

Epochs:  15%|█▌        | 3/20 [01:24<08:00, 28.26s/it, best=16.35, patience=6, val=16.35]

Epochs:  15%|█▌        | 3/20 [01:53<08:00, 28.26s/it, best=14.47, patience=6, val=14.47]

Epochs:  20%|██        | 4/20 [01:53<07:33, 28.34s/it, best=14.47, patience=6, val=14.47]

Epochs:  20%|██        | 4/20 [02:21<07:33, 28.34s/it, best=13.05, patience=6, val=13.05]

Epochs:  25%|██▌       | 5/20 [02:21<07:07, 28.47s/it, best=13.05, patience=6, val=13.05]

Epochs:  25%|██▌       | 5/20 [02:50<07:07, 28.47s/it, best=11.60, patience=6, val=11.60]

Epochs:  30%|███       | 6/20 [02:50<06:40, 28.59s/it, best=11.60, patience=6, val=11.60]

Epochs:  30%|███       | 6/20 [03:19<06:40, 28.59s/it, best=10.71, patience=6, val=10.71]

Epochs:  35%|███▌      | 7/20 [03:19<06:12, 28.67s/it, best=10.71, patience=6, val=10.71]

Epochs:  35%|███▌      | 7/20 [03:50<06:12, 28.67s/it, best=9.91, patience=6, val=9.91]

Epochs:  40%|████      | 8/20 [03:50<05:53, 29.45s/it, best=9.91, patience=6, val=9.91]

Epochs:  40%|████      | 8/20 [04:22<05:53, 29.45s/it, best=9.60, patience=6, val=9.60]

Epochs:  45%|████▌     | 9/20 [04:22<05:33, 30.36s/it, best=9.60, patience=6, val=9.60]

Epochs:  45%|████▌     | 9/20 [04:55<05:33, 30.36s/it, best=9.24, patience=6, val=9.24]

Epochs:  50%|█████     | 10/20 [04:55<05:09, 30.95s/it, best=9.24, patience=6, val=9.24]

Epochs:  50%|█████     | 10/20 [05:27<05:09, 30.95s/it, best=9.24, patience=5, val=9.34]

Epochs:  55%|█████▌    | 11/20 [05:27<04:41, 31.27s/it, best=9.24, patience=5, val=9.34]

Epochs:  55%|█████▌    | 11/20 [05:59<04:41, 31.27s/it, best=9.03, patience=6, val=9.03]

Epochs:  60%|██████    | 12/20 [05:59<04:13, 31.69s/it, best=9.03, patience=6, val=9.03]

Epochs:  60%|██████    | 12/20 [06:31<04:13, 31.69s/it, best=8.85, patience=6, val=8.85]

Epochs:  65%|██████▌   | 13/20 [06:31<03:42, 31.73s/it, best=8.85, patience=6, val=8.85]

Epochs:  65%|██████▌   | 13/20 [06:59<03:42, 31.73s/it, best=8.85, patience=5, val=9.06]

Epochs:  70%|███████   | 14/20 [06:59<03:02, 30.50s/it, best=8.85, patience=5, val=9.06]

Epochs:  70%|███████   | 14/20 [07:28<03:02, 30.50s/it, best=8.31, patience=6, val=8.31]

Epochs:  75%|███████▌  | 15/20 [07:28<02:31, 30.23s/it, best=8.31, patience=6, val=8.31]

Epochs:  75%|███████▌  | 15/20 [07:58<02:31, 30.23s/it, best=8.31, patience=5, val=8.46]

Epochs:  80%|████████  | 16/20 [07:58<02:00, 30.03s/it, best=8.31, patience=5, val=8.46]

Epochs:  80%|████████  | 16/20 [08:28<02:00, 30.03s/it, best=8.31, patience=4, val=8.57]

Epochs:  85%|████████▌ | 17/20 [08:28<01:29, 29.90s/it, best=8.31, patience=4, val=8.57]

Epochs:  85%|████████▌ | 17/20 [08:59<01:29, 29.90s/it, best=8.31, patience=3, val=8.53]

Epochs:  90%|█████████ | 18/20 [08:59<01:00, 30.28s/it, best=8.31, patience=3, val=8.53]

Epochs:  90%|█████████ | 18/20 [09:29<01:00, 30.28s/it, best=8.31, patience=2, val=8.67]

Epochs:  95%|█████████▌| 19/20 [09:29<00:30, 30.26s/it, best=8.31, patience=2, val=8.67]

Epochs:  95%|█████████▌| 19/20 [09:58<00:30, 30.26s/it, best=8.31, patience=1, val=8.45]

Epochs: 100%|██████████| 20/20 [09:58<00:00, 30.06s/it, best=8.31, patience=1, val=8.45]



Epochs:   0%|          | 0/20 [00:00<?, ?it/s]

Epochs:   0%|          | 0/20 [00:29<?, ?it/s, best=32.46, patience=6, val=32.46]

Epochs:   5%|▌         | 1/20 [00:29<09:11, 29.05s/it, best=32.46, patience=6, val=32.46]

Epochs:   5%|▌         | 1/20 [00:58<09:11, 29.05s/it, best=18.64, patience=6, val=18.64]

Epochs:  10%|█         | 2/20 [00:58<08:46, 29.26s/it, best=18.64, patience=6, val=18.64]

Epochs:  10%|█         | 2/20 [01:27<08:46, 29.26s/it, best=16.45, patience=6, val=16.45]

Epochs:  15%|█▌        | 3/20 [01:27<08:16, 29.23s/it, best=16.45, patience=6, val=16.45]

Epochs:  15%|█▌        | 3/20 [01:59<08:16, 29.23s/it, best=14.65, patience=6, val=14.65]

Epochs:  20%|██        | 4/20 [01:59<08:05, 30.32s/it, best=14.65, patience=6, val=14.65]

Epochs:  20%|██        | 4/20 [02:31<08:05, 30.32s/it, best=12.94, patience=6, val=12.94]

Epochs:  25%|██▌       | 5/20 [02:31<07:43, 30.92s/it, best=12.94, patience=6, val=12.94]

Epochs:  25%|██▌       | 5/20 [03:03<07:43, 30.92s/it, best=11.53, patience=6, val=11.53]

Epochs:  30%|███       | 6/20 [03:03<07:15, 31.10s/it, best=11.53, patience=6, val=11.53]

Epochs:  30%|███       | 6/20 [03:34<07:15, 31.10s/it, best=9.94, patience=6, val=9.94]

Epochs:  35%|███▌      | 7/20 [03:34<06:44, 31.14s/it, best=9.94, patience=6, val=9.94]

Epochs:  35%|███▌      | 7/20 [04:01<06:44, 31.14s/it, best=9.30, patience=6, val=9.30]

Epochs:  40%|████      | 8/20 [04:01<05:59, 29.92s/it, best=9.30, patience=6, val=9.30]

Epochs:  40%|████      | 8/20 [04:29<05:59, 29.92s/it, best=8.11, patience=6, val=8.11]

Epochs:  45%|████▌     | 9/20 [04:29<05:21, 29.21s/it, best=8.11, patience=6, val=8.11]


Fold 5: MAE=6.736, RMSE=8.368, R2=0.8492558598518372, best={'head_lr': 0.001, 'backbone_lr': 1e-05, 'weight_decay': 0.0001}

,backbone,fusion,head,mode,cv_mae_mean,cv_mae_std,cv_rmse_mean,cv_rmse_std,cv_r2_mean,cv_r2_std,inner_mae_mean
0,vit_b_16,concat,mlp,last_stage,7.51261,0.780718,9.443722,1.283193,0.798448,0.055833,7.324183

In [5]:
timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
name = f"results_trainable_performance_{timestamp}.csv"
summary_df.to_csv(OUTPUT_DIR / name, index=False)
print("Saved:", OUTPUT_DIR / name)

Saved: results/results_trainable_performance_2026-03-27_09-37-19.csv

In [7]:
df = pd.DataFrame(all_fold_records)
name = f"results_trainable_performance_folds_{timestamp}.csv"
df.to_csv(OUTPUT_DIR / name, index=False)
print("Saved:", OUTPUT_DIR / name)

Saved: results/results_trainable_performance_folds_2026-03-27_09-40-32.csv